### ISSUE TITLE
[BUG] Hiding Min, Max, Close button on window

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#100]
Hiding Min, Max, Close button on window does not disable buttons on window context menu

**Comment by ghost1372** [comment]
can you attach a demo project or screenShot?

**Comment by MichixYT** [comment]
![unknown-128.png](https://user-images.githubusercontent.com/67753196/144974118-92f26097-0cc4-4d7c-b612-31415f8fe496.png)
Maximize button is hidden, but in context menu is still enabled

**Comment by ghost1372** [comment]
Thank you, I am working on it
