### ISSUE TITLE
[BUG] Another mica bug: maximizing window hides taskbar

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#102]
Mica effect disables window animations, and maximizing window hides taskbar

**Comment by LiinxTV** [comment]
Have the same problem

**Comment by ghost1372** [comment]
Fixed in https://github.com/ghost1372/HandyControls/commit/37697c5544717c1a73ce380e4e2691dd66de71dd

**Comment by MichixYT** [comment]
When release with all bug fixes will be released?

**Comment by ghost1372** [comment]
A new version will be released soon. I hope to do this by the end of the week
