### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#104]
Hi, i have read docs and search in source code but i'm lost,i would like to know if its possible with ThemeManager or something else change for exemple all textbox background color in Dark theme, and do the same for Light theme, i don't know if it is possible that's why i ask.

Thanks to guide me to this if it already exist.

Thanks a lot

**Comment by ghost1372** [comment]
Hi
In the ThemeDictionaries (Override predefined colors)

 section in [documentation](https://hosseini.ninja/handycontrol/theme/), you can learn how to overwrite colors.

You need to find the textbox color key name from the code and override it here.
Also you can use this [doc](https://hosseini.ninja/handycontrol/theme/colorPreset/) for override colors

**Comment by LiinxTV** [comment]
Hi,
Thanks for your answer

but its not clear for me, i need to create a new theme or i can edit the default themes ?

**Comment by ghost1372** [comment]
You can edit, with both link i posted

**Comment by ghost1372** [comment]
If you cant do it, i can upload a demo project tomorrow

**Comment by LiinxTV** [comment]
I will try some things,

i tell you in a moment

**Comment by LiinxTV** [comment]
Okay, seems to work. I will close the issue in less than an hour if i don't see any other issue

**Comment by LiinxTV** [comment]
Okay, everything is good, thank you so much for the assistance ! <3
