### ISSUE TITLE
MessageBox Bug

### ISSUE THREAD

**Issue by qwfy168** [ghost1372/HandyControls#105]
**Describe the bug**
调用MessageBox的Ask,Error,Info几个API均会导致崩溃现象

**To Reproduce**
1. 编译库自带Demo,选择控件->窗口->打开消息窗口
2.点击"打开消息窗口"按钮，会崩溃，代码定位到window.cs 392行 _button为null
3. See error

**Expected behavior**
正确现象应为顺利弹出窗口显示
**Screenshots**
**Environment (please complete the following information):**
 - .net: [e.g. 4.8]
 - IDE [e.g. vs2019]
 - Version [3.3.9]

**Additional context**

**Comment by LiinxTV** [comment]
Have the same problem

**Comment by Jie2GG** [comment]
I Have the same problem.

**Environment:**
* .NET 6.0
* Visual Studio 2022
* Version; 3.3.9
