### ISSUE TITLE
[Feature request] Import whole folder to project

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#106]
Hi,

can we import **HandyControls/src/Shared/HandyControl_Shared/** into the main folder of the project ?

I guess yes, but how to do ? what are the modifications ?

The goal is to use HandyControls without installing via NuGet

Cheers

**Comment by ghost1372** [comment]
Hi, Yes you can
you should refrence 

`src\Net_GE45\HandyControl_Net_GE45\HandyControl_Net_GE45.csproj`
