### ISSUE TITLE
changing system theme don't change app theme

### ISSUE THREAD

**Issue by GihanSoft** [ghost1372/HandyControls#107]
**Describe the bug**
changing system theme don't change app theme

**To Reproduce**
```xml
<Application
  x:Class="AbadisDic.App"
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  xmlns:hc="https://handyorg.github.io/handycontrol"
  xmlns:system="clr-namespace:System;assembly=netstandard"
  StartupUri="Views/Win.xaml"
  DispatcherUnhandledException="OnDispatcherUnhandledException">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <hc:Theme />
        <hc:ThemeResources UsingSystemTheme="True" />

        <!-- Other merged dictionaries here -->
      </ResourceDictionary.MergedDictionaries>
      <!-- Other app resources here -->
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

**Expected behavior**
Theme should change

**Screenshots**
![image](https://user-images.githubusercontent.com/35791547/146665002-0d512fbe-be61-443b-a448-18c5e7b06276.png)

**Environment (please complete the following information):**
 - .net: net6.0-windows
 - IDE: vs2022
 - Version: 3.3.9

**addition**
it's sync with windows theme when start but it won't change on runtime

**Comment by ghost1372** [comment]
Hi, Make sure you are using `<hc:Windows` or window/hc:window background is **RegionBrush**
`Background="{DynamicResource RegionBrush}"`

**Comment by GihanSoft** [comment]
`<hc:BlurWindow` `Style="{DynamicResource WindowBlur}"`

**Comment by GihanSoft** [comment]
@ghost1372 even demo app have same problem so I opened issue in main repo

**Comment by ghost1372** [comment]
I think you are using Windows 11
I fixed a problem that caused the sync to not work.
But keep in mind that BlurWindow does not work in Windows 11
https://hosseini.ninja/handycontrol/extend_controls/blurWindow/
![Animation](https://user-images.githubusercontent.com/9213496/146668192-529b984f-b8ce-467a-841c-d208729fdde1.gif)

**Comment by GihanSoft** [comment]
I use windows 10 19042.1348

**Comment by GihanSoft** [comment]
![image](https://user-images.githubusercontent.com/35791547/146668269-a6a0ed35-556f-4913-a266-c12980f8d38a.png)
 @ghost1372

**Comment by ghost1372** [comment]
ohh yes You are right
If you can, clone the new source and try it out

**Comment by GihanSoft** [comment]
It's same. I just `git pull`ed and `dotnet build -c Released`ed and same behavior.

**Comment by ghost1372** [comment]
try with hc:Window or after changing system theme, move or resize blurwindow
i tested in window 11 and everythings worked fine

**Comment by ghost1372** [comment]
@GihanSoft I made a mistake and i commited fix in bugfix/mica brunch, so you need to checkout to bugfix/mica branch.
i pushed a new commit to bugfix/mica so you need to pull it again

**Comment by GihanSoft** [comment]
tanks for fix. I look forward for Nuget release.

**Comment by ghost1372** [comment]
> tanks for fix. I look forward for Nuget release.

new version 3.3.10 released
