### ISSUE TITLE
AutoCompleteTextBox Error

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#109]
Hi,

i have a problem using AutoCompleteTextBox,
when i pick a result, it print this in the text area: **_HandyControl.Controls.AutoCompleteTextBoxItem: Item1_**

Is it a bug ? A misstake ?

Thanks to guide me, i'll be happy to see this working.

code:
                <hc:AutoCompleteTextBox
                    x:Name="Primary"
                    HorizontalAlignment="Left"
                    Margin="133,-176,0,0"
                    HorizontalContentAlignment="Center"
                    Background="#2F3136"
                    Foreground="#F2F3F5"
                    BorderBrush="#5865F2"
                    VerticalAlignment="Top"
                    Width="110"
                    FontSize="14"
                    Height="23">
                </hc:AutoCompleteTextBox>

Thanks <3

**Comment by ghost1372** [comment]
can you upload a demo project? i think you are using wrong code for pick a result

**Comment by LiinxTV** [comment]
[DemoApp.zip](https://github.com/ghost1372/HandyControls/files/7745188/DemoApp.zip)

**Comment by ghost1372** [comment]
@LiinxTV  
Add the following code to the `<hc:AutoCompleteTextBox`

`DisplayMemberPath="Content"`
