### ISSUE TITLE
HandyControl.Controls.MessageBox.Show cause NullReferenceException 

### ISSUE THREAD

**Issue by my522cn** [ghost1372/HandyControls#110]
**Describe the bug**
As I report this bug at:
[https://github.com/HandyOrg/HandyControl/issues/1075](https://github.com/HandyOrg/HandyControl/issues/1075)
it is fine when use HandyControl, but catched a NullReferenceException when using HandyControls

Demo [https://github.com/my522cn/HandyControlProject1](https://github.com/my522cn/HandyControlProject1)
see the HandyControlProject1 and HandyControlProject2 projects

**Comment by ghost1372** [comment]
This issue was recently fixed. A new version will be released by the end of the week
https://github.com/ghost1372/HandyControls/issues/105
