### ISSUE TITLE
[Feature request] Import external demo project

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#111]
Hi, i would like to create Dialogs,
For creating this, i need to implement this in my xaml:

    xmlns:langs="clr-namespace:HandyControlDemo.Properties.Langs"
    xmlns:ex="clr-namespace:HandyControlDemo.Tools.Extension"

but i don't know how to do this.

Do you have a tutorial showing how to do this or can you explain me the steps to follow to be done ? 

Thanks you so much.

**Comment by ghost1372** [comment]
Hi
You do not need these 2 references
Remove theme

`<Border x:Class="HandyControlDemo.UserControl.TextDialog"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:hc="https://handyorg.github.io/handycontrol"
CornerRadius="10"
Width="400"
Height="247"
Background="{DynamicResource RegionBrush}">
<hc:SimplePanel>
<TextBlock Style="{StaticResource TextBlockLargeBold}" Text="please wait"/>
<Button Width="22" Height="22" Command="hc:ControlCommands.Close" Style="{StaticResource ButtonIcon}" Foreground="{DynamicResource PrimaryBrush}" hc:IconElement.Geometry="{StaticResource ErrorGeometry}" Padding="0" HorizontalAlignment="Right" VerticalAlignment="Top" Margin="0,4,4,0"/> 
</hc:SimplePanel>
</Border>`



`namespace HandyControlDemo.UserControl
{
public partial class TextDialog
{
public TextDialog()
{
InitializeComponent();
}
}
}
`

`Dialog.Show(new TextDialog());`
