### ISSUE TITLE
[Feature request] Transfer in Interactive-Dialog

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#112]
Hi Ghost,

I would like to know if it is possible to create a Transfer control in an interactive Dialog control, like this:

![image](https://user-images.githubusercontent.com/64651327/147391494-6e20716b-0b93-4131-930a-4a6136367f53.png)

The goal is to have the same windows but a Transfer control instead of the TextBox control.

Is it possible ?

If yes, can you learn me how to do this ?

Thanks you so much

**Comment by ghost1372** [comment]
here you can learn about transfer and dialog controls
https://hosseini.ninja/handycontrol/extend_controls/transfer/
https://hosseini.ninja/handycontrol/extend_controls/dialog/
so you can build what you want

**Comment by LiinxTV** [comment]
Yes but do you have any example ? i have try and when i click on the button nothing happen

**Comment by ghost1372** [comment]
Unfortunately I do not have any examples

**Comment by LiinxTV** [comment]
I think i have found,now i understand, thanks ♥
