### ISSUE TITLE
Save Transfer state

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#113]
Hi again,

I would like to know how to save the state of right and left items or a Transfer control.

And a last feature that can be cool is to put Name1 at the end of the list when we select it, how to do this ?

![Transfer](https://user-images.githubusercontent.com/64651327/147414481-3dab1f5c-b996-4e6b-9664-e69789893e90.gif)

If at the end, we want to put Name3, it will place it at the 1st position and not at the last, what i want is like a priority thing

Thanks

**Comment by ghost1372** [comment]
To suggest a new feature, please mention it in the main repository
http://github.com/handyOrg/HandyControl/issues
