### ISSUE TITLE
hc:InfoElement.Placeholder Color

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#114]
Hi Ghost,

How to change the foreground of the placeholder in a textbox ?

Thanks.

**Comment by ghost1372** [comment]
Hi @LiinxTV 
you cant change foreground as you can see here
https://github.com/ghost1372/HandyControls/blob/2986911db711e4849695023162c1509fa5e6ff21/src/Shared/HandyControl_Shared/Themes/Styles/Base/TextBoxBaseStyle.xaml#L78

there is no way to change foreground
