### ISSUE TITLE
How to Implement SplashWindow with Stylet?

### ISSUE THREAD

**Issue by SwaroopSomanna** [ghost1372/HandyControls#116]
Im using the provided stylet template for HandyControls project.
I want to add a splash screen to my app. I guess the [doc](https://hosseini.ninja/handycontrol/persianToolkit/splashWindow/) for implementing splash screen (SplashWindow) is valid only for a non-stylet based project because it requires me to override the app's OnStartup method and use MainWindow's code-behind to update Splash Message. I prefer not to use code-behind while using stylet.

So is there a proper way to implement the splash screen in stylet based HandyControls app?

**Comment by ghost1372** [comment]
I have no experience with stylet.
@GF-Huang  can you help?

**Comment by GF-Huang** [comment]
Try this in your `Bootstrapper.cs`:

```cs
public class Bootstrapper : Bootstrapper<RootViewModel> {
    ...

    protected override void Launch() {
        SplashWindow.Instance.AddMessage("Loading main window");
        DoSomethingThatTakesALongTime();
        SplashWindow.Instance.AddMessage("Loading something Witty");
        DoSomethingElseThatTakesALongTime();
        //This will probably never actually get seen
        SplashWindow.Instance.AddMessage("Done!");
        SplashWindow.Instance.LoadComplete();

        base.Launch(); // show the RootView
    }

    ...
}
```

https://github.com/canton7/Stylet/blob/5e97f9e1ea8c45e9d7033e6e7c7ea8ce41c3420a/Stylet/Bootstrapper.cs#L30-L33

https://github.com/canton7/Stylet/blob/5e97f9e1ea8c45e9d7033e6e7c7ea8ce41c3420a/Stylet/BootstrapperBase.cs#L108-L112

**Comment by SwaroopSomanna** [comment]
> Try this in your `Bootstrapper.cs`:
> 
> ```cs
> public class Bootstrapper : Bootstrapper<RootViewModel> {
>     ...
> 
>     protected override void Launch() {
>         SplashWindow.Init(()=> {
>                 MySplashWindow splash = new MySplashWindow();
>                 return splash;
>             });
> 
>         SplashWindow.Instance.AddMessage("Loading main window");
>         DoSomethingThatTakesALongTime();
>         SplashWindow.Instance.AddMessage("Loading something Witty");
>         DoSomethingElseThatTakesALongTime();
>         //This will probably never actually get seen
>         SplashWindow.Instance.AddMessage("Done!");
>         SplashWindow.Instance.LoadComplete();
> 
>         base.Launch(); // show the RootView
>     }
> 
>     ...
> }
> ```
> 
> https://github.com/canton7/Stylet/blob/5e97f9e1ea8c45e9d7033e6e7c7ea8ce41c3420a/Stylet/Bootstrapper.cs#L30-L33
> 
> https://github.com/canton7/Stylet/blob/5e97f9e1ea8c45e9d7033e6e7c7ea8ce41c3420a/Stylet/BootstrapperBase.cs#L108-L112

Its working. Thanks

**Comment by SwaroopSomanna** [comment]
> Try this in your `Bootstrapper.cs`:
> 
> ```cs
> public class Bootstrapper : Bootstrapper<RootViewModel> {
>     ...
> 
>     protected override void Launch() {
>         SplashWindow.Init(()=> {
>                 MySplashWindow splash = new MySplashWindow();
>                 return splash;
>             });
> 
>         SplashWindow.Instance.AddMessage("Loading main window");
>         DoSomethingThatTakesALongTime();
>         SplashWindow.Instance.AddMessage("Loading something Witty");
>         DoSomethingElseThatTakesALongTime();
>         //This will probably never actually get seen
>         SplashWindow.Instance.AddMessage("Done!");
>         SplashWindow.Instance.LoadComplete();
> 
>         base.Launch(); // show the RootView
>     }
> 
>     ...
> }
> ```
> 
> https://github.com/canton7/Stylet/blob/5e97f9e1ea8c45e9d7033e6e7c7ea8ce41c3420a/Stylet/Bootstrapper.cs#L30-L33
> 
> https://github.com/canton7/Stylet/blob/5e97f9e1ea8c45e9d7033e6e7c7ea8ce41c3420a/Stylet/BootstrapperBase.cs#L108-L112

Solved with your code. Thanks.
