### ISSUE TITLE
[Feature request] Add updated acrylic effect for all controls

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#117]
Hi.
I think, that adding updated acrylic effect to all controls would be really usefull.
For example, ms edge has contextmenu with updated acrylic effect
![ms edge](https://user-images.githubusercontent.com/67753196/149006621-68a1a1f9-5499-40f5-baf0-703acf83393c.png)

**Comment by ghost1372** [comment]
I do not know exactly how to do this, but I think they use native controls. Therefore, they can extend the acrylic into their controls.
But in handyControl we have different styles for controls and I do not think that is possible to extend acrylic
