### ISSUE TITLE
Problem with 'ResizeMode' attribute of 'hc:window'

### ISSUE THREAD

**Issue by Jie2GG** [ghost1372/HandyControls#119]
**Describe the bug**
I tried to change the 'ResizeMode' property to 'CanMinimize' when using 'HC :Window'. But this caused the window's control buttons to work incorrectly.

**To Reproduce**
1. Create WPF project
2. Loading HandyControls of nuget
3. Changed MainWindow root section to 'hc:window'
4. add attribute 'ResizeMode', value is 'CanMinimize'
5. run project

**Expected behavior**
working error with 'hc:Window' control button 

**Screenshots**
The video contains an error demo
https://user-images.githubusercontent.com/39112172/149467836-9c80ce46-9055-4c83-b316-e0f46c262fd4.mp4

**Environment (please complete the following information):**
 - .net: [e.g. 6.0]
 - IDE [e.g. vs2022]
 - Version [e.g. 3.3.10]

**Additional context**
None

**Comment by ghost1372** [comment]
I Fixed this bug 20 days ago 
https://github.com/ghost1372/HandyControls/commit/dc97d6e39c4df167b1d9666932e48e88fb3f290d

Today I will release a new version in Nuget (3.3.11)

**Comment by Jie2GG** [comment]
> I Fixed this bug 20 days ago [dc97d6e](https://github.com/ghost1372/HandyControls/commit/dc97d6e39c4df167b1d9666932e48e88fb3f290d)
> 
> Today I will release a new version in Nuget (3.3.11)

Thank you for your work! Looking forward to your new version.
