### ISSUE TITLE
zh-CN language not effect

### ISSUE THREAD

**Issue by sdwdjzhy** [ghost1372/HandyControls#122]
**Describe the bug**
I use `HandyControls` and  `HandyControls.Lang.zh-CN`, version is 3.3.11
then I  `ConfigHelper.Instance.SetLang("zh-cn");`

but `HandyControl.Controls.MessageBox.Show("Ok"); `  show the confirm button is 'Confirm' ,not  '确定'

[test project](https://github.com/sdwdjzhy/testWpf)

What else do I need to do？thanks

**Comment by ghost1372** [comment]
Move this code from MainWindow to App.cs
OnStartup method

 
 `ConfigHelper​.​Instance​.​SetLang​(​"​zh-cn​"​);`

**Comment by sdwdjzhy** [comment]
is this code?
```
        protected override void OnStartup(StartupEventArgs e)
        {
            ConfigHelper.Instance.SetLang("zh-cn");
            base.OnStartup(e);
        }
```

it's alse show 'Confirm'

**Comment by ghost1372** [comment]
its working...
![image](https://user-images.githubusercontent.com/9213496/150672341-d3fc07e6-57a5-4796-bf4d-9ccbe5ec1cd0.png)

**Comment by ghost1372** [comment]
@sdwdjzhy  make sure you have this two reference

```
<PackageReference Include="HandyControls" Version="3.3.11" />
<PackageReference Include="HandyControls.Lang.zh-CN" Version="3.3.11" />
```

**Comment by sdwdjzhy** [comment]
I know the reason.
When I use   .NET framework  4.7.2, the `Nuget` donot add Reference `HandyControl.resources.dll`  to project
csproj need add 
```
    <Reference Include="HandyControl.resources, Version=3.3.0.0, Culture=zh-CN, PublicKeyToken=45be8712787a1e5b">
      <HintPath>..\packages\HandyControls.Lang.zh-CN.3.3.11\lib\net472\zh-CN\HandyControl.resources.dll</HintPath>
    </Reference>
```
so it is Nuget error ?


NET core 5.0 , it is OK .

**Comment by ghost1372** [comment]
@sdwdjzhy  i tested with net 4.7.2 and worked fine
you dont need to add csproj, just install two nuget library.
if you insist on adding csproj you need zh-cn language library. Unfortunately, the language library (zh-cn) is not available as a csproj and you have to install the Nuget package
![image](https://user-images.githubusercontent.com/9213496/150673176-382f2ace-ec51-4853-8c4a-323db7dd3dbf.png)

**Comment by sdwdjzhy** [comment]
maybe i need add other Environment, like NET framework 4.7.2 CHS ???.
In  project [https://github.com/sdwdjzhy/testWpf](https://github.com/sdwdjzhy/testWpf) , I must add zh-cn language library. 

now It is good to run , 能用就好。

**Comment by sdwdjzhy** [comment]
thanks a million
