### ISSUE TITLE
Window disappears when maximized on second screen and Mica is used

### ISSUE THREAD

**Issue by Symbai** [ghost1372/HandyControls#124]
1. Apply Mica to a `hc:Window`
2. Move the window to a second monitor
3. Maximize the window
4. Window completely disappears

This only happens when Mica is used and only on a second monitor. It has something to do with `WmGetMinMaxInfo` method inside `Window.cs`

**Comment by ghost1372** [comment]
thanks but i dont have any second monitor and i cant test this issue

**Comment by xingxing21** [comment]
I faced the same issue when clicking the Restore button of the window that is maximum.
![image](https://user-images.githubusercontent.com/39619359/154626417-225bf982-d4a6-4da6-9e85-008b3d11775b.png)
Control version: 3.3.11
OS: Windows 10
VS: Visual Studio 2019
