### ISSUE TITLE
[Feature request] Add ability to enable mica effect on light/dark mode manually

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#125]
Hi!
Adding ability to enable mica effect on light/dark mode manually would be great!
I mean, something like this:
```cs
MicaHelper.ApplyMicaEffect(object window, bool isDark)
```

**Comment by ghost1372** [comment]
you can do this:
`MicaHelper.ApplyMicaEffect(handle, isDark);`
