### ISSUE TITLE
Typo in "Label" page

### ISSUE THREAD

**Issue by Archeruss** [ghost1372/HandyControls#127]
There is a typo in the word "Label", in the Title of the post (Red circle on the picture)
[https://hosseini.ninja/handycontrol/native_controls/label/index.html]
![image](https://user-images.githubusercontent.com/70743889/153839948-1ff21c41-af43-4bfb-bb24-a3bda580b518.png)

**Comment by ghost1372** [comment]
thank you
typo fixed
