### ISSUE TITLE
Growl always throw TargetInvocationException when I use Task.run with it

### ISSUE THREAD

**Issue by MuoRanLY** [ghost1372/HandyControls#130]
**Describe the bug**
I want to do something out of my wpf main UI thread and used the growl.infoglobal to show the result but when I'm testing the function, Everytime I place my mouse on the popout notice. It throws ou the exception System.Reflection.TargetInvocationException(Win32Exception: 0x80070578)

**To Reproduce**
1. write a async task 
2. click a button to lauch the task
3. use the result to show in growl
4. run

**Expected behavior**
TargetInvocationException

**Screenshots**
![image](https://user-images.githubusercontent.com/73374735/158542869-afcf8f73-eb0c-45d6-b490-cccd8b5e58ce.png)

**Environment (please complete the following information):**
 - .net: 4.7.2
 - IDE vs2022
 - Version 3.3.11

**Additional context**
here is some of my code:
in xaml:
<Button Content="刷新DNS&#13;解析缓存" HorizontalAlignment="Left" VerticalAlignment="Top"  Width="200" Height="100" FontSize="30"  Margin="20,0,0,0" x:Name="Network_RefreshDNS" Click="Network_RefreshDNS_Click"/>
in C#
        string result = "";
        private void Network_RefreshDNS_Click(object sender, RoutedEventArgs e)
        {
            refreshdns();
            if (result.IndexOf("成功") != -1)
            {
                Growl.SuccessGlobal("刷新成功！");
            }
            else
            {
                Growl.InfoGlobal("刷新失败！\n" + result);
            }
        }

async Task refreshdns()
        {
            await Task.Run(() =>
            {
                Process p = new Process();
                p.StartInfo.FileName = "cmd.exe";
                p.StartInfo.UseShellExecute = false;
                p.StartInfo.RedirectStandardInput = true;
                p.StartInfo.RedirectStandardOutput = true;
                p.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
                p.Start();
                p.StandardInput.WriteLine("ipconfig /flushdns");
                p.StandardInput.WriteLine("exit");
                p.StandardInput.AutoFlush = true;
                result = p.StandardOutput.ReadToEnd();
                p.WaitForExit();
            });
        }

these code run well when I use them in winform with notification in toastcontentbuilder()

**Comment by ghost1372** [comment]
Duplicate
https://github.com/HandyOrg/HandyControl/issues/867

https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-1011690174
