### ISSUE TITLE
When setting the property ShowClearButton="True" for the control hc:TextBox, Click on the Clear button throws an exception.

### ISSUE THREAD

**Issue by steveyan00** [ghost1372/HandyControls#131]
**Describe the bug**
When setting the property ShowClearButton="True" for the control hc:TextBox, Click on the Clear button throws an exception. 

**To Reproduce**
1. <hc:TextBox ShowClearButton="True" Text={Binding Variable} />
2. Click the Clear button and enter something. 
3. `7 : ConvertBack cannot convert value '' (type 'String'). BindingExpression:Path=AIntVariable; DataItem='MainViewModel' (HashCode=xxxxxxxx); target element is 'TextBox' (Name=''); target property is 'Text' (type 'String') FormatException:'System.FormatException: Input string was not in a correct format.`

**Expected behavior**
Add a judgment for the empty string. The value can be set to 0 if it is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/13826910/158568333-27b41715-f899-4462-81a2-98c900a3a55e.png)
![image](https://user-images.githubusercontent.com/13826910/158568534-574a39f3-8796-4441-bf18-4ac54b881715.png)
![image](https://user-images.githubusercontent.com/13826910/158755075-6add4f3e-a5f4-45a6-8ce6-29748916e17b.png)
![image](https://user-images.githubusercontent.com/13826910/158567919-b0ce1414-b01f-4aaf-a4b7-ab35600c28da.png)

**Environment (please complete the following information):**
 - .net: 6.0
 - IDE vs2022
 - Version 3.3.11

ps: The above is translated from DeepL.

**Comment by ghost1372** [comment]
https://github.com/ghost1372/HandyControls/issues/48
