### ISSUE TITLE
Come across InvalidOperationException When setting the uri of Imageselector

### ISSUE THREAD

**Issue by MuoRanLY** [ghost1372/HandyControls#132]
**Describe the bug**
Come across InvalidOperationException When setting the uri of Imageselector

**To Reproduce**
if (File.Exists(Properties.Settings.Default.str1))
                {
                    pictureBox1.Uri = new Uri(Properties.Settings.Default.str1);
                }

picturebox1 is the name of a imageselector

**Expected behavior**
System.InvalidOperationException:““Uri”属性注册为只读属性，不使用身份验证密钥则无法修改。”
System.InvalidOperationException:“the 'URI' property is registered as a read-only property and cannot be modified without an authentication key.”

**Screenshots**
![image](https://user-images.githubusercontent.com/73374735/158740915-87eb4430-1959-46fe-9b20-1f7c749be9c2.png)

**Environment (please complete the following information):**
 - .net: 4.7.2
 - IDE vs2022
 - Version 3.3.0

**Comment by MuoRanLY** [comment]
I solve the fuction I want by setting the background to a imagebrush and set it null in imageselected, but I still think the uri{get;set} should be able to be set in the backend

**Comment by ghost1372** [comment]
https://github.com/ghost1372/HandyControls/issues/48
