### ISSUE TITLE
[BUG] Maximazing window with backdrop effect bug

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#134]
### Describe the bug

maximizing a window with backdrop effect sometimes cuts the program window onto the screen 

### Steps to reproduce the bug

double click window to maximaze or maximaze with button, hide app to taskbar and show it again

### Screenshots

Normal:
![obraz](https://user-images.githubusercontent.com/67753196/161587172-8b996b8c-0d69-436f-a258-59ffd9ff3a5c.png)

Bug:
![obraz](https://user-images.githubusercontent.com/67753196/161586494-47b5c5ea-2edf-4fd6-85b8-d0d52da5ab72.png)
(i know that it's black, because method of loading mica effect has changed, but when i have updated in my app method of loading mica effect (also i added acrylic effect and it happens too) and it's still cutting into screen)

### NuGet package version

HandyControls (Custom version) 3.3.11

### IDE

Visual Studio 2022-preview

### Framework type

.Net 6.0

### Windows version

Insider Build (xxxxx)

**Comment by ghost1372** [comment]
i updated MicaHelper with support new types like tabbed, i dont know this issue is fixed or not.
