### ISSUE TITLE
[Feature request] MessageBox backdrop effect

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#138]
Hi! I think that MessageBoxes should have backdrop effect too, that'll be very useful.

**Comment by ghost1372** [comment]
Hi, Since the MessageBox is based on `HandyControl.Controls.Window` and `HandyControl.Controls.Window` is based on `System.Windows.Window`
You can use `SystemBackdropType` property or you can use `SystemBackdropType` AttachedProperty

I didnt test it but this should work

```
<Style TargetType="hc:MessageBox">

<Setter Property="SystemBackdropType" Value="Mica"/>
</Style>
```
