### ISSUE TITLE
[Feature request] Theme change animation

### ISSUE THREAD

**Issue by GliczDev** [ghost1372/HandyControls#140]
Hi, i think that handycontrols should have theme change animation like winui, because now it's only changing color without any effect, and it looks really bad.

**Comment by ghost1372** [comment]
tnx Added
use like this:

internal void UpdateSkin(ApplicationTheme theme)
        {
            **ThemeAnimationHelper.AnimateTheme(HandyControlDemo.MainWindow.Instance, ThemeAnimationHelper.SlideDirection.Top, 0.3, 1, 0.5);**

            ThemeManager.Current.ApplicationTheme = theme;


            **ThemeAnimationHelper.AnimateTheme(HandyControlDemo.MainWindow.Instance, ThemeAnimationHelper.SlideDirection.Bottom, 0.3, 0.5, 1);**

        }
