### ISSUE TITLE
Can not change NumericUpDown's value

### ISSUE THREAD

**Issue by lanzhiquan** [ghost1372/HandyControls#141]
### Describe the bug

https://user-images.githubusercontent.com/11311878/164886286-ce27c06d-6cb6-40ea-9694-b07b8c70b428.mp4

### Steps to reproduce the bug

1. Just use a NumericUpDown control，set decimalplace and set value to it.
2. Input a value between Minimum and Maximum，it seems fails to set the value.

**Comment by ghost1372** [comment]
report it in original [repo](https://github.com/handyOrg/HandyControl/)
