### ISSUE TITLE
hc:Window's property ShowMaxButton will cause the window to fail to restore

### ISSUE THREAD

**Issue by Jie2GG** [ghost1372/HandyControls#144]
### Describe the bug

When I set the ResizeMode of the window to CanMinimize, I set the ShowMaxButton to False, which makes it impossible to click the icon on the taskbar to restore when the form is minimized.

### Steps to reproduce the bug

1. Create WPF project (.net 6.0-windows)
2. Change MainWindow.xaml to my code
3. Change x:Class property
4. Run project
5. Set minimize of window (click minimize button or click taskbar)

My Code: <br/>
```xaml
<hc:Window x:Class="WpfProject1.TestWindow"
           xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
           xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
           xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
           xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
           xmlns:hc="https://handyorg.github.io/handycontrol"
           xmlns:local="clr-namespace:MiniBot.Client.Views"
           mc:Ignorable="d"
           Title="TestWindow"
           Height="450"
           Width="800"
           ResizeMode="CanMinimize"
           ShowMaxButton="False">
</hc:Window>
```

### Expected behavior

If nothing else, you won't be able to restore Window

### Screenshots

None

### NuGet package version

HandyControls (Custom version) 3.3.11

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

### Additional context

None

**Comment by ghost1372** [comment]
everything is working fine and i can restore app from taskbar

**Comment by ancleardream** [comment]
我的最新版本也是不能恢复
