### ISSUE TITLE
[Feature request] Change cdn.jsdelivr.net to unpkg.com

### ISSUE THREAD

**Issue by sdwdjzhy** [ghost1372/HandyControls#145]
**Is your feature request related to a problem? Please describe.**
cdn.jsdelivr.net   cannot opened in my computer( or in China)??

**Describe the solution you'd like**
would you like to change DOC website libs reference , **cdn.jsdelivr.net** to  **unpkg.com** or other cdn? 

thanks

**Comment by ghost1372** [comment]
I updated the documentation theme to [version 8.12.1](https://github.com/next-theme/hexo-theme-next/releases/tag/v8.12.1) In this version the CDN has been changed from **jsdelivr** to **cdnjs** 
I hope this solves your problem.
_Be sure to clear your browser cache to see the changes_
