### ISSUE TITLE
Growl always throw TargetInvocationException when hover on it [.Net Core 3.1]

### ISSUE THREAD

**Issue by blockchain0026** [ghost1372/HandyControls#146]
### Describe the bug

Yes, we can solve this now by adding some code to App.config, but there is no such config in .Net Core 3.1.
This bug exists for 1 year in our project, yet we didn't found a solution, so I'm here to ask if anyone know how this can be solve in .Net Core 3.1 WPF Application.

### Steps to reproduce the bug

1.Show growl in .Net Core WPF App.
2.Put your mouse on it.
3.Crashed with TargetInvocationException.

### Expected behavior

No crash at all.

### Screenshots

![image](https://user-images.githubusercontent.com/63337404/170443452-f6259322-c8ff-4dbb-ac73-94ffdfcb27a6.png)

### NuGet package version

HandyControls (Custom version) 3.3.8

### IDE

Visual Studio 2019

### Framework type

.Net Core 3.1

### Windows version

May 2021 Update (19043)

**Comment by ghost1372** [comment]
report in original [repo](https://github.com/handyOrg/HandyControl/)
