### ISSUE TITLE
App theme not follow system settings when set UsingSystemTheme = true

### ISSUE THREAD

**Issue by JackJCSN** [ghost1372/HandyControls#149]
### Describe the bug

On Windows 10 20H2 there is a theme mode call custom with allow user setting start menu theme and app theme separately.  The app theme follows the start menu theme but not app theme,  when I try to using   <hc:ThemeResources UsingSystemTheme="True" />.

### Steps to reproduce the bug

1.Using Windows 10 20H2 or later version.
2. Go to windows settings → personalization → Colors 
3. Select [Custom] for [Choose your color] drop down
4. Select [Dark] for [Choose your default Windows mode]
5. Select [Light] for [Choose your default app mode]
6. Set <hc:ThemeResources UsingSystemTheme="True" /> in app.xaml for applicaiton with HandyControls
7. start application

### Expected behavior

The application should show follow [Choose your default app mode] setting.
In this case it should be light mode.

### Screenshots

![image](https://user-images.githubusercontent.com/859722/172025548-76d979dc-984a-4ac7-bd86-b1c30ff1bb16.png)

### NuGet package version

HandyControls (Custom version) 3.3.11

### IDE

Visual Studio 2022

### Framework type

.Net Core 3.1

### Windows version

October 2020 Update (19042)

**Comment by ghost1372** [comment]
i added UsingWindowsAppTheme property
