### ISSUE TITLE
Weird black line at top of the program

### ISSUE THREAD

**Issue by NotroDev** [ghost1372/HandyControls#150]
### Describe the bug

Window in minimized view has a weird black line at the top.

### Steps to reproduce the bug

Just create window.
I used this code:
```xaml
<hc:Window x:Class="SkEditorPlus.SettingsWindow"
           xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
           xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
           xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
           xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
           xmlns:hc="https://handyorg.github.io/handycontrol"
           mc:Ignorable="d"
           Title="Ustawienia"
           WindowStartupLocation="CenterScreen"
           ShowTitle="True"
           Height="450" 
           Width="800" Loaded="OnWindowLoad" ResizeMode="NoResize">

    
</hc:Window>
```

### Screenshots

![obraz](https://user-images.githubusercontent.com/77281214/178700235-7e66c7ac-705b-416f-86be-e3ca1cab9193.png)

### NuGet package version

HandyControls (Custom version) 3.3.11

### IDE

Visual Studio 2022

### Framework type

.Net 5.0

### Windows version

Insider Build (xxxxx)

**Comment by ghost1372** [comment]
please report in original repo
https://github.com/handyorg/handycontrol
