### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by NotroDev** [ghost1372/HandyControls#153]
### Describe the bug

Hi.
I updated from 3.3.11 to 3.4.0 and, after launching app, it immediately crashes.
```
System.Windows.Markup.XamlParseException:
"A constructor call for type "HandyControl.Themes.Theme" that matches the specified binding constraints resulted in an exception."
```
It may be not accurate, it's translated.

(When I go back to 3.3.11 everything works)

### Steps to reproduce the bug

1. Update from 3.3.11 to 3.4.0
2. launch app

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 5.0

### Windows version

Insider Build (xxxxx)

**Comment by ghost1372** [comment]
tnx for report
please update to version 3.4.1
https://www.nuget.org/packages/HandyControls/3.4.1
