### ISSUE TITLE
CheckComboBox Select All does not select all - seems to have limitation

### ISSUE THREAD

**Issue by kababu2021** [ghost1372/HandyControls#154]
### Describe the bug

HandyControls v 3.4.1 (however exists on 3.3.11 as well)

Using a CheckComboBox (CheckComboBoxPlus style) with "Clear" and "All" buttons enabled, see that when i click on "All" only the entries which are in focus on the drop down is selected. If I scroll down and select all again, a few more gets selected until some limit. 

Is there a way to get around this issue? OR is it a bug. 

### Steps to reproduce the bug

1. Using this code in an MVVM solution, UsersList has around 50 members.  ClassesList has around 200 members. 
```
        <Expander Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="6" Header="Users" VerticalAlignment="Center" IsExpanded="True" Background="Black" Foreground="White">
            <StackPanel Orientation="Horizontal">
                <hc:CheckComboBox x:Name="CbUsers" VerticalAlignment="Center" Style="{StaticResource CheckComboBoxPlus}" hc:InfoElement.Title="Users" ShowClearButton="True" MinWidth="150" MaxWidth="300" hc:DropDownElement.ConsistentWidth="True" ItemsSource="{Binding Path=UsersList, UpdateSourceTrigger=PropertyChanged}" DisplayMemberPath="UserName" SelectedValuePath="IsSelected" SelectionChanged="CbUsers_SelectionChanged" Margin="0,16,0,0" ShowSelectAllButton="True" />
                <hc:CheckComboBox x:Name="CbClasses" VerticalAlignment="Center" Style="{StaticResource CheckComboBoxPlus}" hc:InfoElement.Title="Users" ShowClearButton="True" MinWidth="150" MaxWidth="300" hc:DropDownElement.ConsistentWidth="True" ItemsSource="{Binding Path=ClassesList, UpdateSourceTrigger=PropertyChanged}" DisplayMemberPath="ClassName" SelectedValuePath="IsSelected" SelectionChanged="CbClasses_SelectionChanged" Margin="0,16,0,0" ShowSelectAllButton="True" />
            </StackPanel>
        </Expander>
```
2. When I select "All" on either of the comboboxes, only the ones in focus gets selected. 

### Expected behavior

Selecting "All" on the CheckCombobox should select all the entries, not just the ones in focus on the drop down. 

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

May 2021 Update (19043)

**Comment by ghost1372** [comment]
report it in Original repo
http://github.com/handyorg/handycontrol

however mybe dup
https://github.com/HandyOrg/HandyControl/issues/1119
