### ISSUE TITLE
NonClientAreaContent can not drag window

### ISSUE THREAD

**Issue by CodingOctocat** [ghost1372/HandyControls#156]
### Describe the bug

NonClientAreaContent can not drag window.

### Steps to reproduce the bug

1. Create a simple `hc:Window`
2. Add `hc:Window.NonClientAreaContent` (content is `Menu`)
3. Try drag the title bar (NonClientAreaContent) to move window，can not do it.

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by CodingOctocat** [comment]
Temporary Solutions:
set `NonClientAreaContent` background `{x:null}`

**Comment by ghost1372** [comment]
mybe you are doing it wrong way...
![Animation2](https://user-images.githubusercontent.com/9213496/184656133-8e7efac0-e5d0-4703-958b-3f720e1881df.gif)

```cs
    <hc:Window.NonClientAreaContent>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition/>
                <ColumnDefinition/>
            </Grid.ColumnDefinitions>
            <StackPanel Height="29">
                <Menu HorizontalAlignment="Left">
                    <MenuItem Header="Header1">
                        <MenuItem Header="Header1"/>
                        <MenuItem Header="Header2"/>
                    </MenuItem>
                    <MenuItem Header="Header2">
                        <MenuItem Header="Header1"/>
                        <MenuItem Header="Header2"/>
                    </MenuItem>
                </Menu>
            </StackPanel>
            <Button HorizontalAlignment="Right" Grid.Column="1" Name="ButtonConfig" Style="{StaticResource ButtonIcon}" Foreground="{DynamicResource PrimaryTextBrush}" hc:IconElement.Geometry="{StaticResource ConfigGeometry}"/>
            
        </Grid>
    </hc:Window.NonClientAreaContent>

```

**Comment by CodingOctocat** [comment]
The reason for the problem is that I did not use Grid, but directly used hc:SimpleStackPanel.
