### ISSUE TITLE
NumericUpDown value not updates by typing

### ISSUE THREAD

**Issue by Kamigakuro** [ghost1372/HandyControls#159]
### Describe the bug

NumericUpDown value not updates by typing keyboard. Value updates only by up/down buttons.

Use nuget v.3.4.1 (not avaliable in selector here).

I installed version 3.3.11 and it's works fine.

`<hc:NumericUpDown Minimum="5"
                              hc:TitleElement.TitlePlacement="Left"
                              hc:TitleElement.TitleWidth="140"
                              Value="{Binding PollTime, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                              Style="{StaticResource NumericUpDownExtend}"
                              Width="400" Margin="0 20 0 0" />`

### Steps to reproduce the bug

1. Create new numericupdown control.
2. Bind Value param to property
3. Change value by typing numerics on keyboard.

### Expected behavior

Binded property must change.

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022-preview, Visual Studio 2022

### Framework type

.Net Core 3.1

### Windows version

October 2020 Update (19042)

**Comment by ghost1372** [comment]
report it in Original repo
