### ISSUE TITLE
`ComboBoxCapsule` style missing in 3.4.1

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#160]
### Describe the bug

![image](https://user-images.githubusercontent.com/4510984/185799623-f7fc09b2-b3b7-472d-809d-9aeebc8b4824.png)

### Steps to reproduce the bug

`<ComboBox Style="{StaticResource ComboBoxCapsule}" />`.

### NuGet package version

HandyControl 3.4.1

### IDE

Visual Studio 2022

### Framework type

.Net 5.0

### Windows version

May 2021 Update (19043)

**Comment by ghost1372** [comment]
@GF-Huang  try new version 3.4.2
