### ISSUE TITLE
Maximized Windows gets off monitor

### ISSUE THREAD

**Issue by Enat0** [ghost1372/HandyControls#162]
### Describe the bug

When we have more than 1 monitor screen and we maximize the windows, it gets off the monitor.

If WindowState is set to "Maximized" it works fine, but if you resize and then maximize it gets off the monitor.

### Steps to reproduce the bug

1. <hc:Window x:Class="testes.MainWindow"
           xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
           xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
           xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
           xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
           xmlns:hc="https://handyorg.github.io/handycontrol"
           mc:Ignorable="d"
           Title="Title" 
           Height="450" 
           Width="800" >
    <Border />
</hc:Window>

2. Maximize the screen
3. 

### Screenshots

(Black line on image is simulation the separation of monitors screens)
 ![image](https://user-images.githubusercontent.com/100444259/186716245-2420163f-0654-41f7-875e-e418618276d0.png)

### IDE

Visual Studio 2022, Visual Studio 2019

### Framework type

.Net 6.0, .Net Framework 4.8

### Windows version

Windows 11 (22000), May 2021 Update (19043)

**Comment by ghost1372** [comment]
report in original repo
