### ISSUE TITLE
EmptyGeometry not show in hc:Empty

### ISSUE THREAD

**Issue by CodingOctocat** [ghost1372/HandyControls#163]
### Describe the bug

EmptyGeometry not show:
![Snipaste_2022-08-27_22-21-15](https://user-images.githubusercontent.com/7220248/187034378-fb782cff-736d-4c93-801f-2e0e90d8a89a.png)

![Snipaste_2022-08-27_22-21-53](https://user-images.githubusercontent.com/7220248/187034380-5eb1890a-6841-4275-8e16-0bfabbdd5fb3.png)

### Steps to reproduce the bug

```XAML
<hc:ToggleBlock IsChecked="{Binding ElementName=lst, Path=HasItems, Mode=OneWay}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch">
    <hc:ToggleBlock.CheckedContent>
        <ListBox Name="lst"/>
    </hc:ToggleBlock.CheckedContent>
    <hc:ToggleBlock.UnCheckedContent>
        <hc:Empty hc:Empty.ShowEmpty="true"/>
        <!-- OR -->
        <!-- 
         <hc:Empty Description="No Data" hc:Empty.ShowEmpty="true">
            <hc:Empty.Logo>
                <Path Data="{DynamicResource EmptyGeometry}"/>
            </hc:Empty.Logo>
        </hc:Empty>
         -->
    </hc:ToggleBlock.UnCheckedContent>
</hc:ToggleBlock>
```

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by ghost1372** [comment]
report in original repo
