### ISSUE TITLE
App crashed after enter chinese characters (with IME candidates visible)

### ISSUE THREAD

**Issue by dogesharp** [ghost1372/HandyControls#166]
### Describe the bug

App crashed after chinese character entered in the new AutoCompleteTextBox control (with IME candidates visible)
VS output:
System.Windows.Data Error: 40 : BindingExpression path error: 'null' property not found on 'object' ''ItemDatabaseBrowserViewModel' (HashCode=14315403)'. BindingExpression:Path=null; DataItem='ItemDatabaseBrowserViewModel' (HashCode=14315403); target element is 'Label' (Name=''); target property is 'BorderBrush' (type 'Brush')

### Steps to reproduce the bug

1.Create AutoCompleteTextBox control in xaml.
2.Try enter some chinese characater with IME
3.When IME show the candidates, It will crashed with high probability.

### Expected behavior

Not crashed.

**Comment by ghost1372** [comment]
report in original repo
