### ISSUE TITLE
Mica material: Incorrect margin values after maximize window not through the button.

### ISSUE THREAD

**Issue by Ladsers** [ghost1372/HandyControls#167]
### Describe the bug

If you maximize the window not through the "Maximize" button, but by dragging the window to the top of the screen, then the margin values of the elements decrease. Also, if you return from full screen mode not through the "Maximize" button, but through "Win + ↓", then the margin values will increase.

If you do not use "Miсa", then everything is fine.

### Steps to reproduce the bug

1. Implement window:
```
<hc:Window x:Class="HandyControlsDemo1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        mc:Ignorable="d"
        SystemBackdropType="Mica"
        Title="MainWindow" Height="250" Width="425">
    <Grid>
        <StackPanel Orientation="Vertical" VerticalAlignment="Bottom">
            <DockPanel HorizontalAlignment="Stretch">
                <Button Content="Button1" Margin="10" HorizontalAlignment="Left"/>
                <Button Content="Button2" Margin="10" HorizontalAlignment="Right"/>
            </DockPanel>
        </StackPanel>
    </Grid>
</hc:Window>
```
2. Press "Win + ↑" to maximize window (or drag the window to the top of the screen).
3. Press "Win + ↓" to back to small window.

### Expected behavior

The margin values of the elements remain the same.

### Screenshots

**"Good" window** (initial state):

![good](https://user-images.githubusercontent.com/37272192/193233670-73017ac6-f89b-4998-8894-37b611cb4668.jpg)

**"Bad" window after "Win + ↑":**

![bad_max](https://user-images.githubusercontent.com/37272192/193234593-917abc33-880b-4987-9fae-102be59f2a5a.jpg)

**"Good" window after clicking on the maximize button:**

![good_max](https://user-images.githubusercontent.com/37272192/193234920-3061fe80-0988-4554-b44f-cd9dbaf63bb1.jpg)

**"Bad" window after "Win + ↓"** (purposefully moved the cursor to the close button):

![bad](https://user-images.githubusercontent.com/37272192/193234263-5335f9f7-a684-4235-85cc-e446f43b87ce.jpg)

### NuGet package version

HandyControl 3.4.0

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22000)

### Additional context

HandyControls: 3.4.2
IDE: JetBrains Rider 2021.3.4

**Comment by ghost1372** [comment]
Fixed
