### ISSUE TITLE
Doubled buttons on transparent background window

### ISSUE THREAD

**Issue by GliczDev** [ghost1372/HandyControls#169]
### Describe the bug

Window with transparent background has doubled buttons

### Steps to reproduce the bug

Create window with transparent background and see effect

### Expected behavior

Not doubled buttons

### Screenshots

![obraz](https://user-images.githubusercontent.com/67753196/193409396-49c4f22f-ef3c-45ca-bfec-75e44a58278a.png)

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022-preview

### Framework type

.Net 6.0

### Windows version

Insider Build (xxxxx)

**Comment by LaptisMinecraft** [comment]
+same doubled buttons

**Comment by MichixYT** [comment]
Okay, so i've made a research, and this should fix this problem
```cs
private const int GWL_STYLE = -16;
private const int WS_SYSMENU = 0x80000;
[DllImport("user32.dll", SetLastError = true)]
private static extern int GetWindowLong(IntPtr hWnd, int nIndex);
[DllImport("user32.dll")]
private static extern int SetWindowLong(IntPtr hWnd, int nIndex, int dwNewLong);

public static void FixBackground(Window window)
{
    var hwnd = new WindowInteropHelper(window).Handle;
    SetWindowLong(hwnd, GWL_STYLE, GetWindowLong(hwnd, GWL_STYLE) & ~WS_SYSMENU);
}
```
