### ISSUE TITLE
NumericUpDown

### ISSUE THREAD

**Issue by ugobe** [ghost1372/HandyControls#170]
### Describe the bug

If I set a Style, the component "disappear" (width or height 0)

### Steps to reproduce the bug

        <Style TargetType="hc:NumericUpDown">
            <Setter Property="VerticalAlignment" Value="Center"/>
            <Setter Property="HorizontalAlignment" Value="Left"/>
            <Setter Property="Width" Value="150"/>
        </Style>

**Comment by ghost1372** [comment]
report it in original repo https://github.com/HandyOrg/HandyControl
