### ISSUE TITLE
[Feature request] Center title

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#174]
It'll be nice, if you'd add easy way to center title, like `CenterTitle="true"` in `hc:Window`

**Comment by ghost1372** [comment]
Please Update to version 3.4.4 and you can use **TitleMargin** Property.
I didn't have enough time to add the property you want, but I added a margin property that will probably meet your needs

**Comment by MichixYT** [comment]
I'm having trouble with this feature. Creating margin from left doesn't work well. Also it collides with nonclientarena

**Comment by ghost1372** [comment]
@MichixYT ohh, I did not have time to test. Can you create a PR? I am very busy and I no longer work with WPF these days.
