### ISSUE TITLE
Property Grid Double does not work and if use keyboard for for double or int the viewmodel data not updated

### ISSUE THREAD

**Issue by techworked** [ghost1372/HandyControls#175]
### Describe the bug

1.Property grid numeric box arrow does not increase or decrease according to decimal
2.Property grid numberic box value not update if used keyboard, Once updates if use arrow button on the box

### Steps to reproduce the bug

1. Create view
2. Create viewmodel with inotifypropertychanged
3. Add double
4. Run and click to type manuall
5. Check the value not returned properly to vm

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by techworked** [comment]
resolved by adding below to the control source.

        else if (e.Key == Key.Return)
        {
            Value = Convert.ToDouble(_textBox.Text);
        }

**Comment by ghost1372** [comment]
report in original repo
