### ISSUE TITLE
AutoCompleteTextBox FilterItems Error

### ISSUE THREAD

**Issue by JiajunDou** [ghost1372/HandyControls#179]
### Describe the bug

`List<Country> countries = new List<Country>()
            {
                new Country(){
                Name= "Afghanistan",
                code= "AF",
                dialCode= "93",
              },
              new Country(){
                Name= "Åland Islands",
                code= "AX",
                dialCode= "358",
              },
              new Country(){
                Name= "Albania",
                code= "AL",
                dialCode= "355",
              },
              new Country(){
                Name= "Algeria",
                code= "DZ",
                dialCode= "213",
              },
              new Country(){
                Name= "American Samoa",
                code= "AS",
                dialCode= "1684",
              },
              ....
           }

country.ItemSource = countries;
<hc:AutoCompleteTextBox x:Name="country" Text="{Binding Item.country}" DisplayMemberPath="Name"/>
`

### Steps to reproduce the bug

none

### Screenshots

![微信截图_20221221120423](https://user-images.githubusercontent.com/42398632/208818860-b66afb83-6e0f-4375-aa2d-d94fa007d461.png)

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22000)

### Additional context

version:3.4.4

**Comment by ghost1372** [comment]
report in original repo
