### ISSUE TITLE
PersianDatePicker: crash on leaving control

### ISSUE THREAD

**Issue by raminmjj** [ghost1372/HandyControls#18]
Hello.

**To Reproduce**
1. type a date, like 1398/10/10
2. press TAB key or click on another control

**Screenshots**
![image](https://user-images.githubusercontent.com/991847/69750209-732c3b80-1161-11ea-89a3-5e1476218e17.png)

Thank you.

**Comment by ghost1372** [comment]
Hi @raminmjj 
I didn't see any problem
If possible, provide a sample project
![3](https://user-images.githubusercontent.com/9213496/69755732-24d16980-116e-11ea-9cc0-adb53871d637.gif)

**Comment by raminmjj** [comment]
I think your windows10 regional format is Persian. to reproduce you most set it to English, like this:
![image](https://user-images.githubusercontent.com/991847/69757862-4c770080-1173-11ea-9d6a-ecfb24ce8f40.png)
*Let me know if you needed a sample to reproducing error 
Thank you.

**Comment by ghost1372** [comment]
tnx @raminmjj 
Fixed in https://github.com/ghost1372/HandyControls/commit/c076c211c9cf7ccf3d81cd98297fdf1d20b5506d
