### ISSUE TITLE
Can't see arrow of Menu when menuitem have child elements

### ISSUE THREAD

**Issue by LiinxTV** [ghost1372/HandyControls#181]
### Describe the bug

``Yooo,

i can't see the arrow when i try to create a menu with submenus,

there is the xaml code i'm using:

`                <Border Background="{DynamicResource SecondaryRegionBrush}" CornerRadius="4" Margin="4" Effect="{StaticResource EffectShadow2}">
                    <DockPanel Width="150" Height="150" Background="#2d2d30" Button.Click="ButtonSkins_OnClick">
                        <Menu Style="{StaticResource MenuBaseStyle}" >
                            <Separator />
                            <MenuItem Header="Sub Items">
                                <MenuItem Header="Child1 SubItem" IsCheckable="true" />
                                <MenuItem Header="Child2 SubItem" IsCheckable="true">
                                    <MenuItem Header="GrandChild2 SubItem" IsCheckable="true" />
                                </MenuItem>
                            </MenuItem>
                        </Menu>
                    </DockPanel>
                </Border>`

What should i do ? Am i doing wrong or is it a bug ?

Thanks

### Steps to reproduce the bug

`                <Border Background="{DynamicResource SecondaryRegionBrush}" CornerRadius="4" Margin="4" Effect="{StaticResource EffectShadow2}">
                    <DockPanel Width="150" Height="150" Background="#2d2d30" Button.Click="ButtonSkins_OnClick">
                        <Menu Style="{StaticResource MenuBaseStyle}" >
                            <Separator />
                            <MenuItem Header="Sub Items">
                                <MenuItem Header="Child1 SubItem" IsCheckable="true" />
                                <MenuItem Header="Child2 SubItem" IsCheckable="true">
                                    <MenuItem Header="GrandChild2 SubItem" IsCheckable="true" />
                                </MenuItem>
                            </MenuItem>
                        </Menu>
                    </DockPanel>
                </Border>`

### Screenshots

[https://prnt.sc/dJvzokggknH9](url)

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

**Comment by ghost1372** [comment]
we dont have arrow
https://ghost1372.github.io/handycontrol/native_controls/menu/

mybe you shoulds set icon for menu item
