### ISSUE TITLE
App sometimes gets cut when maximized 

### ISSUE THREAD

**Issue by NotroDev** [ghost1372/HandyControls#182]
### Describe the bug

App sometimes gets cut in left top corner when maximized.

### Steps to reproduce the bug

1. Create window like this https://github.com/NotroDev/SkEditorPlus/blob/main/SkEditorPlus/MainWindow.xaml.cs
2. Minimize it
3. Maximize it by moving it to screen's top

### Screenshots

![image](https://user-images.githubusercontent.com/88681446/216437913-b4cc36e9-bbb8-4c72-a69f-eca22546d458.png)

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

### Additional context

HandyControls' version is 3.4.4.

**Comment by NotroDev** [comment]
I think I fixed it with this code:
```cs
[DllImport("user32.dll")]
static extern IntPtr GetWindow(IntPtr hWnd, uint wCmd);
const uint GW_HWNDNEXT = 2;

[DllImport("user32.dll")]
[return: MarshalAs(UnmanagedType.Bool)]
static extern bool SetForegroundWindow(IntPtr hWnd);

[DllImport("user32.dll")]
[return: MarshalAs(UnmanagedType.Bool)]
static extern bool IsWindowVisible(IntPtr hWnd);


private void OnSizeChanged(object sender, SizeChangedEventArgs e)
{
    FixCut();
}

private void FixCut()
{
    if (WindowState == WindowState.Maximized)
    {
        IntPtr hWnd = new WindowInteropHelper(Application.Current.MainWindow).Handle;

        IntPtr hNext = hWnd;
        do
            hNext = GetWindow(hNext, GW_HWNDNEXT);
        while (!IsWindowVisible(hNext));

        SetForegroundWindow(hNext);

        Activate();
    }
}

private void Window_StateChanged(object sender, EventArgs e)
{
    FixCut();
}
```

**Comment by ghost1372** [comment]
Tnx bit i am not working with wpf anymore
