### ISSUE TITLE
HandyControl!HandyControl.Tools.Interop.InteropMethods::GetWindowPlacement”的调用导致堆栈不对称

### ISSUE THREAD

**Issue by asine** [ghost1372/HandyControls#183]
### Describe the bug

托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“HandyControl!HandyControl.Tools.Interop.InteropMethods::GetWindowPlacement”的调用导致堆栈不对称。原因可能是托管的 PInvoke 签名与非托管的目标签名不匹配。请检查 PInvoke 签名的调用约定和参数与非托管的目标签名是否匹配。”

### Steps to reproduce the bug

Microsoft Visual Studio Community 2022 (64 位) - Current
版本 17.4.4
.net framework 4.8 x86
如果target 为anycpu or x64 应该没有问题。
如果为x86就会出现上面的错误。
如果用handycontrols3.3.8之前的版本也不会出错。用之后的版本就会报上面错误。

you can debug attact sln.
[WpfApp1.zip](https://github.com/ghost1372/HandyControls/files/10705555/WpfApp1.zip)

### NuGet package version

HandyControls (Custom version) 3.4.0

### Framework type

.Net Framework 4.8

### Windows version

May 2021 Update (19043)

**Comment by hanlilong** [comment]
我也是，咋办？

**Comment by asine** [comment]
你英语好不好？好的话，发一个英文的issue，这样作者可能会修复此问题。

**Comment by asine** [comment]
@ghost1372 I test change as attach pic code ,can resolve this error. pls test it.
![图片](https://user-images.githubusercontent.com/3248918/221391103-0ffd7754-5e32-446f-909c-5b46aedea699.png)
