### ISSUE TITLE
Could not load type...

### ISSUE THREAD

**Issue by iverdiver** [ghost1372/HandyControls#184]
### Describe the bug

I've added the HandyControls with and 's' at the end, version 3.4.4 to my Project.
It works fine if I use the "old method when adding the code to App.xaml:

  <Application.Resources>
      <ResourceDictionary>
          <ResourceDictionary.MergedDictionaries>
              <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml"/>
              <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
          </ResourceDictionary.MergedDictionaries>
      </ResourceDictionary>
  </Application.Resources>

But if I use the either the "new" method for both HandyControl and HandyControls:
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
             <hc:ThemeResources/>
             <hc:Theme/>
         </ResourceDictionary.MergedDictionaries>
     </ResourceDictionary>
  </Application.Resources>

<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <hc:Theme Name="HandyTheme"/>
         </ResourceDictionary.MergedDictionaries>
     </ResourceDictionary>
  </Application.Resources>

It does not work.

I want to change some of the theme colors so I'm using the unofficial version (again -> 3.4.4), but I get the following error;

![image](https://user-images.githubusercontent.com/5990307/218965632-520f96ad-b1ee-427a-b709-b1339eaa9cff.png)

For some reason it states that it can't load the type from version 3.4.0.0!
It seems like a bug to me, but I could be wrong.
Any help appreciated

### Steps to reproduce the bug

Add nuget packet HandyControls 3.4.4
<PackageReference Include="HandyControls" Version="3.4.4" />

Add to App.xaml
 <Application xmlns:hc="https://handyorg.github.io/handycontrol">
      <Application.Resources>
          <ResourceDictionary>
              <ResourceDictionary.MergedDictionaries>
                  <hc:ThemeResources/>
                  <hc:Theme/>
              </ResourceDictionary.MergedDictionaries>
          </ResourceDictionary>
      </Application.Resources>
  </Application>

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by AIUbi** [comment]
Try to delete bin,obj directories, and then rebuild also check dependencies and update them manually.

**Comment by iverdiver** [comment]
Thanks for the reply @AIUbi. 
I just tried your advice, unfortunately it did not resolve the issue.
