### ISSUE TITLE
It's there any plan or roadmap to release new version?

### ISSUE THREAD

**Issue by JeremyWu917** [ghost1372/HandyControls#185]
Hi bro,

It's there any plan or roadmap to release new version?

Thanks ☕

**Comment by JeremyWu917** [comment]
@ghost1372 
I need fix this issues [here](https://github.com/HandyOrg/HandyControl/issues/1328)
Thanks

**Comment by ghost1372** [comment]
> @ghost1372 
> I need fix this issues [here](https://github.com/HandyOrg/HandyControl/issues/1328)
> Thanks 

Hi, i am busy and I no longer work with WPF

**Comment by JeremyWu917** [comment]
> > @ghost1372
> > I need fix this issues [here](https://github.com/HandyOrg/HandyControl/issues/1328)
> > Thanks
> 
> Hi, i am busy and I no longer work with WPF

OK, thanks

**Comment by ghost1372** [comment]
@JeremyWu917 
new version published

**Comment by JeremyWu917** [comment]
> @JeremyWu917 new version published

Thank you so much ☕
