### ISSUE TITLE
I found the language not effect

### ISSUE THREAD

**Issue by sdwdjzhy** [ghost1372/HandyControls#188]
### Describe the bug

[Test Projects](https://github.com/sdwdjzhy/TestHandyControls)

I found that when using the old project template, the language class library cannot be loaded。

The  test projects has two project .they are NET 472, 
the  [TestHandyControls] not working properly 
the  [TestHandyControlsSDKTemplate] working ok

### Steps to reproduce the bug

Create project with  "WPF Application (.Net framework)" not "WPF Application".

I test .Net framework 4.7.2.

```
    /// <summary>
    /// App.xaml 的交互逻辑
    /// </summary>
    public partial class App : Application
    {

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            ConfigHelper.Instance.SetLang("zh-CN");
        }
    }

 // in MainWindow
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            HandyControl.Controls.MessageBox.Show("adsfasdf");
        }
```

### Expected behavior

i hope to the button's content is "确定" not "Confirm".

### Screenshots

![image](https://user-images.githubusercontent.com/10877772/224276455-c737261a-4725-45d8-9f5d-35c2eff5277d.png)

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.7.2

### Windows version

May 2021 Update (19043)

**Comment by ghost1372** [comment]
You should install language pack
https://www.nuget.org/packages/HandyControls.Lang.zh-cn

**Comment by sdwdjzhy** [comment]
![image](https://user-images.githubusercontent.com/10877772/224450646-da6390be-31db-47ee-8ae0-e2c842a350bd.png)

it is.

I use the latest version of HandyControls
