### ISSUE TITLE
[Feature request] Validation.ErrorTemplate constistency

### ISSUE THREAD

**Issue by dthoeni** [ghost1372/HandyControls#190]
Some controls like the ComboBox don't use "Validation.ErrorTemplate" to show error messages.
This makes styling very difficult without overriding the whole control template.

Please use Validation.ErrorTemplate for error displaying.

**Comment by ghost1372** [comment]
HandyControl no longer supports these and has been replaced by ValidationRules
check docs:
https://ghost1372.github.io/handycontrol/tools/ValidationRule/index.html?highlight=valida

https://ghost1372.github.io/handycontrol/extend_controls/textBox/index.html?highlight=valida#Validation

**Comment by ghost1372** [comment]
sorry, 
report it in original repo

**Comment by dthoeni** [comment]
I did
