### ISSUE TITLE
Timbar with multiple values

### ISSUE THREAD

**Issue by pankajsaini1987** [ghost1372/HandyControls#191]
hi, i want to use this timebar for my video player seekbar.
here i have 5 different videos of a day.
now i have created a timbar with 24 hour scale, and bind the data that i have for a day, like highlight the color if i have data for that hour otherwise no highlight.
issue
1. now i want to bind that data for multiple, so i need multiple liines in this timebar to highlight
2. i want context menu on this for right click option that i want to build
3. i want to add range selector in this timebar.
please guide me or help me how to achieve this.

**Comment by ghost1372** [comment]
report it in original repo
