### ISSUE TITLE
The color of TabControlInLine is unexpected

### ISSUE THREAD

**Issue by moomiji** [ghost1372/HandyControls#193]
### Describe the bug

It's correct color when using `syncWithSystem` in Official version 3.4.0 as shown in the figure below:
![image](https://user-images.githubusercontent.com/35213527/230776734-f0fdca42-d57a-4ec5-846c-31b529a51cd1.png)

But the PrimaryBrush is not correct in HandyControls from 3.4.1 to 3.4.5 when setting `UsingSystemTheme`:
![image](https://user-images.githubusercontent.com/35213527/230778464-620882fc-af4b-4aff-905b-805463e1d35a.png)

### Steps to reproduce the bug

setup:
```
ThemeManager.Current.UsingSystemTheme = true;
```

Also reproduce in HandyControlDemo
![image](https://user-images.githubusercontent.com/35213527/230779924-882da9ca-fbd5-4ab5-ad33-df47cbd572d7.png)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22621)

**Comment by ghost1372** [comment]
When you are using UsingSystemTheme, i think we are using os accent color! (I cant remember exactly) so check your os accent color if true, this is by design

**Comment by moomiji** [comment]
> When you are using UsingSystemTheme, i think we are using os accent color! (I cant remember exactly) so check your os accent color if true, this is by design

Thank you for such a quick reply!

Yeah, the os accent color and the PrimaryBrush is right. This only happens on TabControlInLine, and other controls using PrimaryBrush don't use preset colors.
![image](https://user-images.githubusercontent.com/35213527/230782191-9bb91f05-a63c-4c16-8f42-a87d017f7110.png)

I tried to go back to version 3.3.11, everything is ok.
![image](https://user-images.githubusercontent.com/35213527/230781861-ef0b0fd1-f27f-4e95-9c8d-15670b34e5ed.png)


Is that reproduced in your HandyControlDemo?

**Comment by ghost1372** [comment]
I am no longer ue wpf i moved to winui 3, i think you can overwrite primarybrush (probably there is a accentcolor propert if nox you can overwrite by key)

**Comment by moomiji** [comment]
Oh, I know what happan!

In TabControlBaseStyle.xaml, the BorderBrush switched from PrimaryBrush to TitleBrush. The commit is https://github.com/HandyOrg/HandyControl/commit/eb2779fa2a4d83c1425b60a92c50b3a10eecee69

And different from https://github.com/HandyOrg/HandyControl/blob/624545376fbadcf6f7a36f1ab863706359808fa6/src/Shared/HandyControl_Shared/Themes/Theme.cs#L236 . 

HandyControls didn't deal with TitleBrush when using UsingSystemTheme in https://github.com/ghost1372/HandyControls/commit/cb9fc91982d62691bdbb6cbf417627ec6e64d598

**Comment by ghost1372** [comment]
@moomiji  sorry for so long delay.
i fixed it in https://github.com/ghost1372/HandyControls/commit/f8bd3452cd4b357858d882b1d9d4d34d0765cd14
![image](https://github.com/ghost1372/HandyControls/assets/9213496/47e37d5a-1cdc-436e-83c2-da4f2be5b743)
