### ISSUE TITLE
[Feature request] Ability to cancel TabItem's Closing event

### ISSUE THREAD

**Issue by NotroDev** [ghost1372/HandyControls#196]
**Is your feature request related to a problem? Please describe.**
Currently, I don't see any way to stop the `hc:TabItem.Closing` event from occurring without modifying the control. I would need this to add a confirmation screen to this event.

**Describe the solution you'd like**
Some event handlers can be used with `System.ComponentModel.CancelEventArgs` argument and be cancelled with `e.Cancel = true;`. I think it would be great to have the ability to do something like this.

**Comment by ghost1372** [comment]
report it in original repo
