### ISSUE TITLE
Memory leak when using ComboBox

### ISSUE THREAD

**Issue by kirill-782** [ghost1372/HandyControls#197]
### Describe the bug

If a combobox appears in the window, then after closing the window, the window instance will not be collected by the garbage collector

### Steps to reproduce the bug

1) Create a window
2) Add to the Combobox window
3) Open the window
4) Close the window

### Expected behavior

Window instance available for garbage collection

### Screenshots

Link graph when window is closed (leak)
![image](https://user-images.githubusercontent.com/7936957/235324151-90fa5fa8-e716-4962-ae38-9094e06bfe38.png)

Link graph when window is open
![image](https://user-images.githubusercontent.com/7936957/235324187-4cbfc636-4cfd-4892-beb5-79766f8c3cc4.png)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2019

### Framework type

.Net Framework 4.7.2

**Comment by PIE-kimty** [comment]
Yes, I agree. I also had a hard time finding the memory leak because of the same problem. Currently, the existing WPF ComboBox is being used or replaced with another ComboBox.
But other features work very well. thank you

Visual Studio 2022
.NET 6.0
Windows 11

**Comment by ghost1372** [comment]
report it in original repo
