### ISSUE TITLE
AutoCompleteTextBox VerticalContentAlignment not work

### ISSUE THREAD

**Issue by CodingOctocat** [ghost1372/HandyControls#199]
### Describe the bug

AutoCompleteTextBox VerticalContentAlignment not work

### Steps to reproduce the bug

```XAML
<hc:AutoCompleteTextBox VerticalAlignment="Center"
                        VerticalContentAlignment="Center"/>
```

### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/7220248/ac9e1a2e-7f7d-44e1-8a77-e700a4a0a13c)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net 7.0

### Windows version

Windows 11 (22621)

**Comment by ghost1372** [comment]
report it in original repo

**Comment by CodingOctocat** [comment]
I tested it.Some problems are only reproduced in HandyControls.
