### ISSUE TITLE
[Feature request] Input controls add IsError, ErrorStr, VerifyFunc, ErrorTemplate DP

### ISSUE THREAD

**Issue by CodingOctocat** [ghost1372/HandyControls#200]
HandyControl (e.g ComboBox) support IsError, ErrorStr, VerifyFunc, and Why doesn't this library have these dependency properties anymore?

**Comment by ghost1372** [comment]
HandyControl no longer supports these and has been replaced by ValidationRules
check docs:
https://ghost1372.github.io/handycontrol/tools/ValidationRule/index.html?highlight=valida

https://ghost1372.github.io/handycontrol/extend_controls/textBox/index.html?highlight=valida#Validation

Also, the Official HandyControl does not support these properties.

Unfortunately, a new version has not been released for HandyControl for more than 1 year, so you do not have the latest changes and are using the old version from more than 1 year ago.
But HandyControls is periodically updated and includes the latest changes.
so you should be ready for migrating to Validation Rules...
