### ISSUE TITLE
ErrorTemplate is not aligned with TitleElement.TitleWidth

### ISSUE THREAD

**Issue by CodingOctocat** [ghost1372/HandyControls#201]
`ErrorTemplate` is not aligned with `TitleElement.TitleWidth`,but `HandyControl` is aligned.

**HandyControls**:
![image](https://github.com/ghost1372/HandyControls/assets/7220248/62d52768-9ef3-4caf-8de5-f5182ef01d3f)

**HandyControl**:
![image](https://github.com/ghost1372/HandyControls/assets/7220248/39dd9a58-5d1c-4c51-870d-c62ea8263351)

**Comment by ghost1372** [comment]
report it in original repo
