### ISSUE TITLE
CoverViewItem will make XAML designer busy

### ISSUE THREAD

**Issue by ALINGCAT** [ghost1372/HandyControls#204]
### Describe the bug

My VS2022's version is 17.6.5.

### Steps to reproduce the bug

1.I create a new UserControl
2.Replace the default Grid or take hc:CoverView and hc:CoverViewItem inside
3.popup a window and tell me "XAML设计器正忙"("XAML Designer is busy" my IDE's language is Chinese)
4.IDE is not responding. I can't do anything.
5.restart IDE and lose change.(because I can't save my xaml file)

### Screenshots

![Snipaste_2023-07-26_10-20-52](https://github.com/ghost1372/HandyControls/assets/30259069/a10ae1a9-4de6-4866-b733-9f5a1795c809)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.6.1

### Windows version

May 2021 Update (19043)

### Additional context

VS and Blend have the same problem.

**Comment by ghost1372** [comment]
report it in original repo
