### ISSUE TITLE
hc:ComboBox dropdown automatically close as soon as opened with mouse click 

### ISSUE THREAD

**Issue by DineshSolanki** [ghost1372/HandyControls#206]
### Describe the bug

DropDown of combobox opens and closes automatically, even without making a selection, it stays open until mouse is pressed, as soon as mouse is lifted, the dropdown closes.

it is only happening in version 3.4.5

### Steps to reproduce the bug

1. Add the menu to a window
2. Add combox as menu item
3. try to open drop-down of combobox

### Expected behavior

the dropdown should stay open until I make a selection.

### Screenshots

![FoliCon_OTmorGuk0L](https://github.com/ghost1372/HandyControls/assets/15937452/a270b2a2-b394-457f-b288-8e3dade0151f)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22621)

**Comment by ghost1372** [comment]
report it in original repo
