### ISSUE TITLE
In DataGrid ShowSelectAllButton is too small

### ISSUE THREAD

**Issue by RaoHammas** [ghost1372/HandyControls#207]
In DataGrid `ShowSelectAllButton` is too small and looks weird. I've tried using `HandyControl` instead and in that the size looks fine but in `HandyControls` it looks like this 👇

![image](https://github.com/ghost1372/HandyControls/assets/16499626/f431dffd-1cc3-40ab-b979-7d3990c7450a)

### Steps to reproduce the bug

Create a new project using ` .Net 8` and add HandyControl's latest nuget package
create a data grid and set ` hc:DataGridAttach.ShowSelectAllButton="True"` attached property to true.  

            <DataGrid
                hc:DataGridAttach.ApplyDefaultStyle="True"
                hc:DataGridAttach.ShowRowNumber="True"
                hc:DataGridAttach.ShowSelectAllButton="True"
                AutoGenerateColumns="False"
                FontSize="14"
                HeadersVisibility="All"
                ItemsSource="{Binding Products}"
                RowHeaderWidth="60"
                Style="{StaticResource DataGridBaseStyle}">
                <DataGrid.Columns>
                    <DataGridTextColumn
                        Width="*"
                        Binding="{Binding Name}"
                        Header="Name" />
                    <DataGridTextColumn Binding="{Binding Qty}" Header="Qty" />
                    <DataGridTextColumn
                        Width="*"
                        Binding="{Binding Price}"
                        Header="Price" />
                    <DataGridTextColumn Header="Disc%" />
                    <DataGridTextColumn Header="Disc" />
                    <DataGridTextColumn Header="Tax" />
                </DataGrid.Columns>
            </DataGrid>

### Expected behavior

`ShowSelectAllButton` icon size should be a lil bigger.

### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/16499626/a85678e5-f14c-48a7-a6d8-3abc347b9efb)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022-preview

### Framework type

.Net 7.0

### Windows version

Windows 11 (22621)

**Comment by ghost1372** [comment]
report it in original repo

**Comment by RaoHammas** [comment]
> report it in original repo

Sorry what? the issue is in HandyControls...

**Comment by ghost1372** [comment]
> > report it in original repo
> 
> Sorry what? the issue is in HandyControls...

Oh sorry, I did not pay attention

I don't have enough time to work on WPF
I will open this issue to work on it in the future if I have a chance
