### ISSUE TITLE
Menu popup horizontal offset is disturbed in full screen

### ISSUE THREAD

**Issue by RaoHammas** [ghost1372/HandyControls#208]
### Describe the bug

The menu popup's horizontal offset has some value that pushes it a lil away from the left side. 
see below,

![image](https://github.com/ghost1372/HandyControls/assets/16499626/3bdbcc9c-53c2-4f0a-9a46-5b95627c42d8)

### Steps to reproduce the bug

Create new project
Add Menu inside `NonClientAreaContent` and ad some menu items.
Run app and maximize the window
Click menu and you will see menu popup pushed from left a few pixels

### Expected behavior

it should not have a horizontal offset value.

### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/16499626/8bd382f2-b8eb-4300-9dc4-ee19c9905c85)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022-preview

### Framework type

.Net 7.0

### Windows version

Windows 11 (22621)

**Comment by ghost1372** [comment]
report in original repo
