### ISSUE TITLE
Provide a Demo App

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [ghost1372/HandyControls#21]
Please provide a demo app so we can experiment what's possible and what component library have in a demo app.

**Comment by ghost1372** [comment]
@HamidRezaAshkiyan  سلام پروژه دمو تو سورس موجود هستش اگر این منظورتون نیست، لطفا بیشتر توضیح بدید
ممنون

**Comment by HamidRezaAshkiyan** [comment]
چشم الان بررسی میکنم  به شما اطلاع میدم
خیلی ممنون بابت کامپوننت های عالی که طراحی کردین

**Comment by ghost1372** [comment]
@HamidRezaAshkiyan  خواهش میکنم کار اصلی رو اقای نبیان انجام دادن
درضمن مستندات (هنوز کامل نیست) رو هم میتونید اینجا پیدا کنید ممکنه به دردتون بخوره
http://github.com/ghost1372/HandyControl/wiki
https://ghost1372.github.io/
