### ISSUE TITLE
TabControl Item header text not working

### ISSUE THREAD

**Issue by RamiGamalMahmoud** [ghost1372/HandyControls#210]
### Describe the bug

When I am using the extended TabControl the tabitem content disappeared, and if I used the native TabControl the header content comes back but I can not sue the TabItem close button

### Steps to reproduce the bug

![image](https://github.com/ghost1372/HandyControls/assets/43172711/b8d5c322-c4e5-441e-bc2f-74a532f50001)

### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/43172711/bbbe2bd6-fb83-4650-a1e3-6ed1cf93f8d0)
![image](https://github.com/ghost1372/HandyControls/assets/43172711/0e7aa292-56a1-4b43-bdb5-de0c5327a62e)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net 7.0

**Comment by ghost1372** [comment]
report it in original repo
