### ISSUE TITLE
Calendar related controls foreground not overridable

### ISSUE THREAD

**Issue by heisenberg-cooks** [ghost1372/HandyControls#211]
### Describe the bug

None of the brushes defined in colorsdark and colorslight allow overriding the foreground of the calendar items (e.g., days when looking at month view).  So far, this seems to be the only extended control that has this issue.  I am using my own custom theme manager, and i have copied all of the brushes defined in themes folder.

If i explicitly load "Dark" theme before using my theme manager, the calendar looks fine, but if i switch to my "light" theme, the text color does not change.

I'm pretty sure this control's text foreground wasn't hooked up to a brush.

### Steps to reproduce the bug

1. Add calendar node
2. Add override for one of the foreground brushes (not sure which one but i've tried them all and nothing changes the color).

### Expected behavior

A brush within brushes should be able to override the foreground of the text in the calendar related controls.

### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/130884420/94b023bc-b49f-4127-a35e-117239a3c705)

### NuGet package version

HandyControls (Custom version) 3.4.5

**Comment by ghost1372** [comment]
report it in original repo
