### ISSUE TITLE
`DataGrid.InputBindings` with `MouseBinding` throw exception

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#213]
### Describe the bug

At `3.4.5` it works no exception, `3.5.0` throw exception: `ArgumentException: "MouseAction" property was registered by "MouseBinding".`

### Steps to reproduce the bug

Just use this code to reproduce:

```cs
<DataGrid>
  <DataGrid.InputBindings>
    <MouseBinding MouseAction="LeftDoubleClick" 
                  Command="{x:Static SystemCommands.CloseWindowCommand}" />
  </DataGrid.InputBindings>
</DataGrid>
```

### NuGet package version

HandyControls (Custom version) 3.5.0

### IDE

Visual Studio 2022

### Framework type

.Net 8.0

### Windows version

Windows 11 (22621)

**Comment by DineshSolanki** [comment]
came here for this, same is happening in only v3.5.0

**Comment by ghost1372** [comment]
Guys, I don't have enough time to work with WPF, I didn't add anything new, just synced with the main repo.
So can you check prs and send a pr?

**Comment by DineshSolanki** [comment]
tried the code after reverting 8e1e8263f7918a142dc61f731fb9399f6927ed3e, seems to resolve this issue

**Comment by ghost1372** [comment]
it seems that fixed
https://github.com/HandyOrg/HandyControl/issues/1526
