### ISSUE TITLE
ImageBrowser 在3.5版(net8)时出现报错

### ISSUE THREAD

**Issue by gqm2023** [ghost1372/HandyControls#216]
### Describe the bug

使用new ImageBrowser(New Uri("https://xxx.com/xxx.jpg",UriKind.Absolute)) 时会出现图片地址错误的警告，在3.4.5及之前的版本无此问题。

### Steps to reproduce the bug

1.升级到3.5.0后直接出现警告并无法执行。
2.退回到3.4.5后一切正常

### NuGet package version

None

### IDE

Visual Studio 2022

**Comment by xingzuhui** [comment]
大哥这作者来自伊朗,你用英文提问.
Bro,you should issue in English.
Like this,
Waining of image Uri error when i am using "new ImageBrowser(New Uri("[https://xxx.com/xxx.jpg",UriKind.Absolute](https://xxx.com/xxx.jpg%22,UriKind.Absolute)))"" .  It didn't happen in 3.4.5 and before.

**Comment by xingzuhui** [comment]
本来中国人做的,但是中国人不更新了.

**Comment by ghost1372** [comment]
report it in original repo
but it seems that issue fixed
https://github.com/HandyOrg/HandyControl/commit/66ad32f52a18c4b6a22aed711042eac8a6e9bf92
