### ISSUE TITLE
Pagination Index goes wrong after cutomizing the PaginationButtonStyle

### ISSUE THREAD

**Issue by PieceOfFall** [ghost1372/HandyControls#218]
## Environment:
    .net8
    HandyControls 3.5.0

### I use Pagination in my project
```xaml
                <!-- 分页组件 -->
                <StackPanel Grid.Row="2" Orientation="Horizontal" HorizontalAlignment="Center">
                    <hc:Pagination MaxPageCount="{Binding MaxPageCount}" PageIndex="{Binding PageIndex,Mode=TwoWay}" AutoHiding="True"
                                   Margin="20" PaginationButtonStyle="{StaticResource PaginationButtonStyle}">
                        <i:Interaction.Triggers>
                            <i:EventTrigger EventName="PageUpdated">
                                <i:InvokeCommandAction 
                                    CommandParameter="页码更新"
                                    Command="{Binding ExecuteCommand}"/>
                            </i:EventTrigger>
                        </i:Interaction.Triggers>
                    </hc:Pagination>
                </StackPanel>
```
### , and set PaginationButtonStyle:
```xaml

        <Style x:Key="PaginationButtonStyle" TargetType="RadioButton" BasedOn="{StaticResource MaterialDesignChoiceChipPrimaryOutlineRadioButton}">
            <Setter Property="Margin" Value="3"/>
            <Setter Property="FontSize" Value="20" />
            <Setter Property="Height" Value="30" />
        </Style>
    </UserControl.Resources>
```
###  I find the first Index also being selected:
![image](https://github.com/ghost1372/HandyControls/assets/85009059/0fefc5d9-b5cd-49ba-98d6-d1da0bf4a3c5)
### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/85009059/3704ed00-b572-4b4e-9737-42166a99c79c)
![image](https://github.com/ghost1372/HandyControls/assets/85009059/8d4d68d5-74a8-492d-a76e-0a8e32e4d4fb)

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 7.0

### Windows version

Windows 11 (22000)

**Comment by ghost1372** [comment]
report it in original repo

**Comment by PieceOfFall** [comment]
Thus，could you please close your entrance to report bug here ?

**Comment by ghost1372** [comment]
This is only for reports about the custom version, we have already informed here
https://github.com/ghost1372/HandyControls/issues/48
