### ISSUE TITLE
CheckComboBox 没有ShowClearButton 属性导致 绑定异常

### ISSUE THREAD

**Issue by 52017126** [ghost1372/HandyControls#219]
### Describe the bug

原版 样式 有 ShowClearButton属性绑定，现在扩展版没有了，但扩展版CheckComboBox 应用的还是原版的样式，在XAML里还有绑去绑定查找ShowClearButton属性，导致保定失败,几条数据无所谓 ，但一旦有几十条，上百条就卡死了。__

### Steps to reproduce the bug

用MVVM模式 绑定使用 CheckComboBox 就行了，会提示 查找绑定ShowCloseButton 失败

### Expected behavior

不报错正常绑定，

### Screenshots

![{5518BB66-4AF8-4ca5-8940-C55ECA78A425}](https://github.com/ghost1372/HandyControls/assets/7858197/7e375b03-8604-4c71-875e-c36655c14647)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22621), Windows 11 (22000)

**Comment by ghost1372** [comment]
report it in original repo
