### ISSUE TITLE
مشکل استروک در متن فارسی

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [ghost1372/HandyControls#22]
یک مشکل در outline textbox وجود داره که زمانی که استروک به متن میدیم داخل متن هم میفته 
![image](https://user-images.githubusercontent.com/38791873/71957448-06499e00-3203-11ea-921f-0476f04c6af8.png)

البته در این عکس یه مشکل دیگه outline textbox هم وجود داره که متن فارسی رو برعکس میکنه و حتما باید flow driection چپ به راست بهش بدیم تا درست بشه 

این دو مشکل در متن فارسی خیلی ازاردهندست و عملا نمیزاره ازش استفاده مفیدی بشه.

**Comment by ghost1372** [comment]
@HamidRezaAshkiyan  سلام
ممنون بابت گزارش، پیگیری میکنم اما احتمال میدم خود کنترل به این صورت طراحی شده باشه، قبلا هم مشکلاتی از این دست بود که بعدا مشخص شد عمدی به این صورت طراحی شدن
