### ISSUE TITLE
The color of TabControlIn is unexpected

### ISSUE THREAD

**Issue by luluxiaoyu** [ghost1372/HandyControls#220]
### Describe the bug

The color of TabControlIn is unexpected
seem like #193
but i'm not use ThemeManager.Current.UsingSystemTheme = true;

### Steps to reproduce the bug

just use tabcontrol in handycontrol style
Style="{StaticResource TabControlInLine}" or Style="{StaticResource TabControlCapsuleSolid}

### Screenshots

![image](https://github.com/ghost1372/HandyControls/assets/58876608/fb564beb-5699-42d2-b183-4ac6b9c00a58)
![image](https://github.com/ghost1372/HandyControls/assets/58876608/9733c792-19fa-42f8-9ec9-5be048c2bfb9)

### NuGet package version

HandyControls (Custom version) 3.4.5

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22621)

**Comment by ghost1372** [comment]
Thanks for the report, I don't work with wpf anymore but will definitely fix this.
I See Green Color in TabItem, Do you expect it to be blue instead of the green?

**Comment by luluxiaoyu** [comment]
> Thanks for the report, I don't work with wpf anymore but will definitely fix this. I See Green Color in TabItem, Do you expect it to be blue instead of the green?

The accentcolor I set is green, and I want the blue to turn green

**Comment by ghost1372** [comment]
> > Thanks for the report, I don't work with wpf anymore but will definitely fix this. I See Green Color in TabItem, Do you expect it to be blue instead of the green?
> 
> The accentcolor I set is green, and I want the blue to turn green

Fixed in https://github.com/ghost1372/HandyControls/commit/f8bd3452cd4b357858d882b1d9d4d34d0765cd14

![image](https://github.com/ghost1372/HandyControls/assets/9213496/38a3cf9f-768e-4f04-8386-e7fb4fecca15)

**Comment by luluxiaoyu** [comment]
> > > Thanks for the report, I don't work with wpf anymore but will definitely fix this. I See Green Color in TabItem, Do you expect it to be blue instead of the green?
> > 
> > 
> > The accentcolor I set is green, and I want the blue to turn green
> 
> Fixed in [f8bd345](https://github.com/ghost1372/HandyControls/commit/f8bd3452cd4b357858d882b1d9d4d34d0765cd14)
> 
> ![image](https://private-user-images.githubusercontent.com/9213496/316022436-38a3cf9f-768e-4f04-8386-e7fb4fecca15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTQwOTksIm5iZiI6MTcxMTExMzc5OSwicGF0aCI6Ii85MjEzNDk2LzMxNjAyMjQzNi0zOGEzY2Y5Zi03NjhlLTRmMDQtODM4Ni1lN2ZiNGZlY2NhMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTMyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc1NTc2YzUwZjZkM2Y2OWJkMjBjYTEyYzlkOTBhMDlmN2IyOGE3ZDY0YWVlNzQ2NjQyYjA4MDM4N2RiNGFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RFljpG_b_zV_4d5n8F1wUu1x1njNTvxhgcYWPnl1LRk)

thx
