### ISSUE TITLE
DateTimePicker Confirmed Event

### ISSUE THREAD

**Issue by Mghobadid** [ghost1372/HandyControls#27]
hi, how can i use DateTimePicker Confirmed Event ?
pls,provide a example.

**Comment by ghost1372** [comment]
hi @Mghobadid  this control Does not have this event, but i think you can use `SelectedDateTimeChanged` event

```
        <hc:DateTimePicker SelectedDateTimeChanged="DateTimePicker_SelectedDateTimeChanged"/>
```
and
```
private void DateTimePicker_SelectedDateTimeChanged(object sender, FunctionEventArgs<System.DateTime?> e)
        {
            MessageBox.Show(e.Info.Value.ToString());
        }
```

**Comment by Mghobadid** [comment]
thanks, but this event fired many times , like open datepicker dialog , initialize datepicker,close it and ... ! so this event not suitable. 
what about the event in this doc?
[https://github.com/ghost1372/HandyControl/wiki/DateTimePicker-Control](https://github.com/ghost1372/HandyControl/wiki/DateTimePicker-Control)

**Comment by ghost1372** [comment]
@Mghobadid  This is a mistake and the wiki has not been updated for a while, Please see the new documentation [here](https://ghost1372.github.io/handycontrol/extend_controls/dateTimePicker/)  
But it's a good suggestion If I have the opportunity, I will add the event
