### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by Youshida-sama** [ghost1372/HandyControls#29]
Hello!
You can add Russian localization?
I can send for you edited file with translated messages.

**Comment by Youshida-sama** [comment]
[Lang.ru.resx.txt](https://github.com/ghost1372/HandyControls/files/4509100/Lang.ru.resx.txt)
Rename to 'Lang.ru.resx'.
Thank you in advance!

**Comment by ghost1372** [comment]
Hi @Youshida-sama 
Yes, very excellent
I will add soon, thank you

**Comment by ghost1372** [comment]
tnx @Youshida-sama  russian language added
