### ISSUE TITLE
TR Language Support

### ISSUE THREAD

**Issue by Taiizor** [ghost1372/HandyControls#30]
I translate for Turkish language support.
Please, I would be glad if you add it.

**Comment by Taiizor** [comment]
Minor errors have been fixed.

[HandyControl_Shared.zip](https://github.com/ghost1372/HandyControls/files/4519380/HandyControl_Shared.zip)

**Comment by Taiizor** [comment]
HandyControlDemo TR Language Support

[HandyControlDemo_Shared.zip](https://github.com/ghost1372/HandyControls/files/4519495/HandyControlDemo_Shared.zip)

**Comment by Taiizor** [comment]
HandyControlDemo - Minor errors have been fixed.

[HandyControlDemo_Shared.zip](https://github.com/ghost1372/HandyControls/files/4519568/HandyControlDemo_Shared.zip)

**Comment by Taiizor** [comment]
HandyControlDemo - Minor errors have been fixed.

[HandyControlDemo_Shared.zip](https://github.com/ghost1372/HandyControls/files/4520101/HandyControlDemo_Shared.zip)

**Comment by Taiizor** [comment]
Turkey Flag

![tr](https://user-images.githubusercontent.com/41683699/80056807-c26a7280-852d-11ea-9c14-5671bbde8013.png)

**Comment by ghost1372** [comment]
Hi @Taiizor  thank you very much
It will be added to the project soon👍

**Comment by Taiizor** [comment]
After the translation is added to the project,
I will carry out the necessary checks on the project
and forward it again after the arrangements.

**Comment by ghost1372** [comment]
> HandyControlDemo - Minor errors have been fixed.
> 
> [HandyControlDemo_Shared.zip](https://github.com/ghost1372/HandyControls/files/4522822/HandyControlDemo_Shared.zip)

tnx updated in [PR](https://github.com/HandyOrg/HandyControl/pull/373/commits/35d136bdd89e5ce0f3c096a7c156b943079d4f02)
