### ISSUE TITLE
SimpleText control bug

### ISSUE THREAD

**Issue by qrai** [ghost1372/HandyControls#32]
**Problem**
Problem is in `SimpleText` control.
When you changing *Foreground* property it simply not changes the color of the text.
(I use the latest version of HandyControls on NuGet)

**Comment by ghost1372** [comment]
Hi @qrai 
I didn't see any problem 🤔
(Visual Studio Designer Doesn't Work Precisely You may not see changes being made while designing)
![Untitled](https://user-images.githubusercontent.com/9213496/80473380-4de36980-895b-11ea-99f1-026752f32ca0.png)

**Comment by qrai** [comment]
Yea, I see, the problem was in VS Designer.
