### ISSUE TITLE
How to set default selected sidemenuitem?

### ISSUE THREAD

**Issue by qrai** [ghost1372/HandyControls#33]
I would like the one sidemenuitem to be selected as default.
I just have 4 pages, I use sidemenu as navigation between these pages.
When I run my app none of sidemenuitems not selected. But I would like one to be.
I tried `IsSelected` property, but it works weird:
-As I start app everything is ok (it's selected)
-But when I click another sidemenuitem: there are two selected sidemenuitems.
[image link](https://drive.google.com/open?id=1bf6lcyxkyn0acMMSoD0Sbpj_hb7vMvq3)

**Comment by ghost1372** [comment]
Thank you @qrai 
can you upload a simple project?

**Comment by qrai** [comment]
[link to the window code](https://drive.google.com/open?id=1IcnJSTUvpy71MYIwQcKOeVt3_0SugoIO)

**Comment by ghost1372** [comment]
tnx @qrai  this is a bug
We will solve this problem soon

**Comment by ghost1372** [comment]
fixed in https://github.com/HandyOrg/HandyControl/commit/518afc884596da202114b90004a8ac18100e51d1
