### ISSUE TITLE
[Q] hc:TabControl.OnPageClosed event?

### ISSUE THREAD

**Issue by qrai** [ghost1372/HandyControls#38]
I just didn't found an event for page close.
Is it implemented? help.
Sorry for the simple question.

**Comment by ghost1372** [comment]
closed event exist in tabitem
```
<hc:TabControl>
            <hc:TabItem Closed="TabItem_Closed" Header="test"/>
            <hc:TabItem Header="test"/>
        </hc:TabControl>
```

**Comment by ghost1372** [comment]
or you can use like this:
`        <hc:TabControl hc:TabItem.Closed="TabControl_Closed">
`

**Comment by qrai** [comment]
thanks, idk if it's issue, but hc:TabItem.Closed event (inside TabControl) gives TabControl as sender
