### ISSUE TITLE
Custom treeviewitem foreground is not changed when is selected in treeview

### ISSUE THREAD

**Issue by qrai** [ghost1372/HandyControls#40]
I have an issue.
I created a custom treeviewitem content:
- StackPanel
  - Image
  - SimpleText

By default the SimpleText foreground is black.
But when I choose that treeviewitem in a tree it's still black foreground.
How can I fix that?
Update: I found a selected event but how to update the color to black again when the node is unselected?
Update 2: I found an unselected event lol, now I have a problem: double click event on treeview not works anymore.
Update 3: i added DoubleClick event to treeviewitem instead, it works.

And now I have the same problem about the treeviewitem with the childs:
You can see my code for the changing colors of treeviewitem content:
```cs
item.Selected += delegate (object sender, RoutedEventArgs e) { lbl.Fill = new SolidColorBrush(Color.FromRgb(255, 255, 255)); };
item.Unselected += delegate (object sender, RoutedEventArgs e) { lbl.Fill = new SolidColorBrush(Color.FromRgb(0,0,0)); };
item.LostFocus += delegate (object sender, RoutedEventArgs e) { lbl.Fill = new SolidColorBrush(Color.FromRgb(0, 0, 0)); };
```
When the item is selected: item text color changed to white (gets blue bg)
When the item is unselected: item text changed to black (gets white bg)
When the item is lost focus: item text changed to black(gets gray bg)
Everything works well, but only with the treeviewitems that didn't have any children.
The items that contain some children are:
- Getting white text color when its children are selected (But getting black text color when its children are lost focus)

Please fix that bug. I think the bug isn't in theme. It's in the events. Maybe a treeviewitem with children does wrong events?

All that i do right now is to handle a treeviewitem with an icon. Maybe there easier ways?

**Comment by ghost1372** [comment]
use TextBlock insted of SimpleText, SimpleText used for internal usage, TextBlock handle foreground in selected and unselected automatically, anyway if you want to customize more you can write trigger
```
<DataTemplate>
                    <StackPanel>
                        <Image/>
                        <TextBlock Text="{Binding}">
                            <TextBlock.Style>
                                <Style>
                                    <Style.Triggers>
                                        <DataTrigger Binding="{Binding IsSelected, RelativeSource=
{RelativeSource FindAncestor, AncestorType={x:Type TreeViewItem}}, FallbackValue=False}" 
Value="True">
                                            <Setter Property="TextBlock.Foreground" Value="Red" />
                                        </DataTrigger>
                                    </Style.Triggers>
                                </Style>
                            </TextBlock.Style>
                        </TextBlock>
                    </StackPanel>
                </DataTemplate>
```

**Comment by qrai** [comment]
Thanks for the answer but I have another problem.
I explored the treeview logic and selection in it works like:
1. Selected node `Selected` event called
2. Selected node parent `Selected` event called
3. and etc (parent of the parent , etc selected event called)

So, it's a bit wrong that the parent of selected node is too called as selected.
I need to avoid this login in my project.
I have a treeview with items, every item has a unique type (folder, file)
And each item handles the `OnSelected` event when an item selected event called, the custom context menu is set to treeview. (context menu depends on item unique type)

But because of that treeview logic, my code isn't working.
How can I avoid an `OnSelected` event call of *Real Selected Node* parent?

**Comment by ghost1372** [comment]
Please report this issue [here](https://github.com/handyorg/handycontrol/issues)
