### ISSUE TITLE
The Dynamic Multi Language does not works at design time, is it meet expectation?

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#49]
Am I missing something? If not, I've written a language manager a few years ago, it's used for .NET Framework WPF that supports runtime switching languages and displays well on the designer, if you want, I can provide the code here.

![image](https://user-images.githubusercontent.com/4510984/111418269-5767f280-8722-11eb-952b-455eacc3516f.png)

**Comment by ghost1372** [comment]
Hi, yes design time is not supported
It will be great if you share your code

**Comment by GF-Huang** [comment]
@ghost1372  I had post a very simple demo: https://github.com/GF-Huang/MultiLanguageDemo, please read it.

**Comment by ghost1372** [comment]
Thanks for the codes. 
but I was unable to implement it in the hc. Can you send a PR?
The structure is a little different. I tried different methods and ways, but so far I have not succeeded
Right now I have found another library that looks great And also supports design mode. (https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension)
what do you think? Should we add the design mode to the current localization or delete the current localization and replace this library?

**Comment by GF-Huang** [comment]
> but I was unable to implement it in the hc. ...
> The structure is a little different. I tried different methods and ways, but so far I have not succeeded
> ...

I'm a little confused. Does my demo works well for you?

**Comment by GF-Huang** [comment]
`LocalizationExtension` removed? I can't find it in master branch.

![image](https://user-images.githubusercontent.com/4510984/111549438-21c11900-87b7-11eb-99aa-2764847b86ba.png)

**Comment by ghost1372** [comment]
> > but I was unable to implement it in the hc. ...
> > The structure is a little different. I tried different methods and ways, but so far I have not succeeded
> > ...
> 
> I'm a little confused. Does my demo works well for you?

Yes, your demo works well, but I could not implement it on current hc localization.
the master branch has nothing, Everything is in the develop branch

**Comment by GF-Huang** [comment]
The develop branch I had try to build a few hours ago, but getting build error, so I try to switch master. Can the latest commit build success now?

**Comment by ghost1372** [comment]
> The develop branch I had try to build a few hours ago, but getting build error, so I try to switch master. Can the latest commit build success now?

Are you sure? Because i dont see any error and The build is successful
![Screenshot_۲۰۲۱۰۳۱۸-۱۰۴۱۰۸_Chrome.jpg](https://user-images.githubusercontent.com/9213496/111586916-c43cc480-87d6-11eb-8ab3-cfbc97a29048.jpg)

**Comment by GF-Huang** [comment]
Project `HandyControl_Net_GE45` build success, but `HandyControlDemo_Net_GE45` failed due to [Compiler Error CS0104](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0104?f1url=%3FappId%3Droslyn%26k%3Dk(CS0104)):

![image](https://user-images.githubusercontent.com/4510984/111587929-d67e2900-87fd-11eb-8090-cf09d7fbcfec.png)

**Comment by ghost1372** [comment]
> Project `HandyControl_Net_GE45` build success, but `HandyControlDemo_Net_GE45` failed due to [Compiler Error CS0104](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0104?f1url=%3FappId%3Droslyn%26k%3Dk(CS0104)):
> 
> ![image](https://user-images.githubusercontent.com/4510984/111587929-d67e2900-87fd-11eb-8090-cf09d7fbcfec.png)
> 
> Because I want to debug the localization issue by demo project, so I need to build it success.

Oh You are right, There are probably two classes with the same name
I will solve the problem as soon as I get home
Also you can checkout this commit

https://github.com/ghost1372/HandyControls/commit/0b3425cc45c5d6be42c53a5473df15e42c2a0b8e

Probably can be compiled without any problems

**Comment by ghost1372** [comment]
@GF-Huang  checkout latest commit i fixed compile issue

**Comment by GF-Huang** [comment]
Got it, build success now.

**Comment by GF-Huang** [comment]
Another question, I always get syntax error in every `xaml` file, but no error for building, do you same to me? Or my vs2019 bug?

![image](https://user-images.githubusercontent.com/4510984/111638565-67242b80-8835-11eb-8fb0-6879eb63f452.png)

**Comment by ghost1372** [comment]
yes this is same
The bug is related to vs, I think it's because of the SharedProject
![image](https://user-images.githubusercontent.com/9213496/111645503-00434a00-8816-11eb-86b4-198cb1ed6af8.png)

**Comment by GF-Huang** [comment]
I use [this](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-at-design-time?view=vs-2019#debug-a-custom-xaml-control-at-design-time-by-attaching-to-xaml-designer) method to debug the design mode codes, I found that the `LocalizationProvider` of `LocalizationManager` is `null` at design time, this cause the issue which make design time not work. 

Since there is no way to know in advance what the `ILocalizationProvider` is (provided by the library's user), it seems that the only way to do this is to change the `ILocalizationProvider` interface to remind the user to provide a design-time instance. 

For example:

```cs
public interface ILocalizationProvider
{
    object Localize(string key);
    ILocalizationProvider GetDesignTimeInstance(); // add this
}
```

what do you think this?

![image](https://user-images.githubusercontent.com/4510984/111673077-8fbc1d80-8855-11eb-94d3-0a321950a808.png)

**Comment by ghost1372** [comment]
It looks right
I looked at the code [here](https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension) again

https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/244f915125315ef429cfb724e0e5170cbe5ca102/src/Providers/ResxLocalizationProviderBase.cs#L241

they seem to be looking for the Visual Studio exe file and implementing operations on it. They seem to be doing exactly what you said.
But the code in this library seems a bit complicated and dirty 😅
I have to find a better and easier way to do this

**Comment by ghost1372** [comment]
@GF-Huang 
I have been working on this since last night, The current localizer structure needs to change, Instead of changing the structure, we can use WPFLocalizationExtension library Which provides more features. One of its most important features is the ability to use multiple resources I want to bring this library to HC.
I made some changes to it so if the current localizer is removed users will not face Breaking Changes 

The changes I made:
- Add CultureChanged event
- Change DesignCulture from string to Culture
- Automatically find assembly name

I put the demo project here for you to take a look
[WpfApp4.zip](https://github.com/ghost1372/HandyControls/files/6169979/WpfApp4.zip)

**Comment by GF-Huang** [comment]
Great! The demo works well! 🚀

**Comment by GF-Huang** [comment]
What happen? 😅 

![image](https://user-images.githubusercontent.com/4510984/112341202-2d06ce00-8cfc-11eb-8a7e-a8c26cf9c93f.png)
![image](https://user-images.githubusercontent.com/4510984/112341296-414acb00-8cfc-11eb-9fc9-9d91eef69de1.png)
![image](https://user-images.githubusercontent.com/4510984/112341318-47d94280-8cfc-11eb-930d-0d5ffeebce23.png)

**Comment by ghost1372** [comment]
Does not work?
The last time I tested it worked
Maybe it's the vs designer's problem
Rebuild project, maybe it will be solved

**Comment by GF-Huang** [comment]
Rebuild not solve.. But somewhere works, somewhere not works.

![image](https://user-images.githubusercontent.com/4510984/112409504-93b7d600-8d54-11eb-867e-f671487a58d5.png)

**Comment by GF-Huang** [comment]
[StyletApp1.zip](https://github.com/ghost1372/HandyControls/files/6201776/StyletApp1.zip)

Here the demo, both not work.. Not the stylet issue. 😢

**Comment by GF-Huang** [comment]
I found that if I specifies `DefaultDictionary` and `DefaultAssembly` explicit, it works in the demo project, but **not** works in my real project.

![image](https://user-images.githubusercontent.com/4510984/112426762-747c7100-8d73-11eb-8ed5-4fb766f015f8.png)

Another question is that if I change `Grid` to `StackPanel` in designer, it will give me error until I build or refresh.

https://user-images.githubusercontent.com/4510984/112427219-2caa1980-8d74-11eb-8e13-d82218189fe9.mp4

**Comment by ghost1372** [comment]
Designer problems are related to Visual Studio Unfortunately, for such cases, the designer needs to be refreshed There is no other solution.
I tested your demo, it works.
I used it in my own projects and it worked without any problems, you will probably miss something

![11](https://user-images.githubusercontent.com/9213496/112432240-3aed3b00-8d5e-11eb-8ff6-82d1c566787c.gif)

**Comment by GF-Huang** [comment]
Add a `ContextMenu` or `Menu` in the `ShellView.xaml`, you will see a binding error log at the run time.

**Comment by ghost1372** [comment]
@GF-Huang  ContextMenu breaks the Parent/Child relationships towards the host control or window. Therefore, the assembly and dictionary attached properties can't be read out there. This issue is not a bug.

Solution: Add the assembly and dictionary to the key, according to the: "Assembly:Dictionary:Key" notation. Or add these attached properties to a suitable place in the ContexMenu visual (sub-)tree
try this:

`<MenuItem Header="{hc:Localization StyletApp1:Resource:Test}"/>`

or this
```
<ContextMenu hc:ResxLocalizationProvider.DefaultAssembly="StyletApp1" hc:ResxLocalizationProvider.DefaultDictionary="Resource">
            <MenuItem Header="{hc:Localization Test}"/>
            <MenuItem Header="asd"/>
            <MenuItem Header="asd"/>
        </ContextMenu>
```
Both work without problems

**Comment by GF-Huang** [comment]
Is there any way to set `hc:ResxLocalizationProvider.DefaultAssembly` and `hc:ResxLocalizationProvider.DefaultDictionary` global? Rather than set them each `.xaml` and `ContextMenu`.

**Comment by ghost1372** [comment]
this should work
```
<Style TargetType="ContextMenu" BasedOn="{StaticResource ContextMenuBaseStyle}">
    <Setter Property="hc:ResxLocalizationProvider.DefaultAssembly" Value="StyletApp1"/>
    <Setter Property="hc:ResxLocalizationProvider.DefaultDictionary" Value="Resource"/>
</Style>
```

**Comment by GF-Huang** [comment]
Also for `Window` and `UserControl`?

**Comment by ghost1372** [comment]
> Also for `Window` and `UserControl`?

You can test, it should work

**Comment by GF-Huang** [comment]
Seems the `Grid` also has this issue, after I add these, one error remains:

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'Grid' (Name=''); target property is 'Parent' (type 'DependencyObject')`

![image](https://user-images.githubusercontent.com/4510984/112438364-c7115980-8d82-11eb-8f4b-a83806ab79d2.png)

**Comment by ghost1372** [comment]
I used the grid in the demo, but I do not see any error
![Untitled](https://user-images.githubusercontent.com/9213496/112439549-dd112100-8d66-11eb-920e-75a7696a291a.png)

**Comment by GF-Huang** [comment]
What differences of `hc:LocalizationBinding` vs `hc:Localization`?

**Comment by ghost1372** [comment]
The intention is to use hc:LocalizationBinding in Multibinding:
```
<MultiBinding Converter={hc:StringFormatConverter}>
        <hc:LocalizationBinding Path="assembly:resource:key" />
         <Binding Test/>
         <Binding Test2/>
    </MultiBinding>
```

**Comment by GF-Huang** [comment]
`MenuItem.Header` is defined as `object` rather `string`, in this case `hc:StringFormatConverter` will cause `Only string as targettype is allowed`. 😢 

![image](https://user-images.githubusercontent.com/4510984/112455530-c7b2eb80-8d94-11eb-803a-a01d5bdc47db.png)

**Comment by ghost1372** [comment]
@GF-Huang  Take a look at [StringFormatConvert](https://github.com/ghost1372/HandyControls/blob/develop/src/Shared/HandyControl_Shared/HandyControls/DynamicLanguage/ValueConverters/StringFormatConverter.cs). Maybe you can create a suitable converter for yourself

**Comment by GF-Huang** [comment]
Maybe modify this to allow targetType is `object` will be better.

![image](https://user-images.githubusercontent.com/4510984/112457764-08abff80-8d97-11eb-878c-4c9b5199c343.png)

**Comment by GF-Huang** [comment]
`hc:ToggleBlock` also need explicit set `DefaultAssembly` and `DefaultDictionary`... 😢 It seems that many controls need to do this, which seems very inconvenient.

**Comment by GF-Huang** [comment]
> I used the grid in the demo, but I do not see any error

I found that is the `ToggleBlock` issue.

![image](https://user-images.githubusercontent.com/4510984/112487673-dfe83200-8db7-11eb-8805-0592085c42e7.png)

**Comment by ghost1372** [comment]
@GF-Huang  I am very sorry to have used this library without further research.
Its development seems to have stopped. I found a better alternative.
For now, I want to test it so that we do not have these problems again.
I will try to add to HC much sooner and we will have a nuget version soon.
I apologize for these problems

**Comment by GF-Huang** [comment]
At least we've learned from practice that it's not perfect. 😄

**Comment by ghost1372** [comment]
Exactly, everything has problems and solutions come at a cost 😅
