### ISSUE TITLE
[Feature request] Add a IValueConverter property to EnumBindingSourceExtension

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#51]
Sometimes we need to binding the `enum` which defined in 3rd library or built-in .NET, so we can't add attributes to it.

Now, I use **2 converters** to solves this issue when using `ComboBox`. If `EnumBindingSourceExtension` supports `IValueConverter` for each `enum` value, I can delete the `CipherTypeArrayConverter` and only use **1 converter**.

![image](https://user-images.githubusercontent.com/4510984/111888168-08b5a380-8a15-11eb-8b73-40cf22e33af0.png)

![image](https://user-images.githubusercontent.com/4510984/111888206-60eca580-8a15-11eb-990e-8043694a8e37.png)

**Comment by ghost1372** [comment]
So if an enum did not have a description attributes, we should convert it to a string, Do you mean this?

**Comment by GF-Huang** [comment]
Yes, convert to a custom string which not equals to the `enumValue.ToString()`.

**Comment by ghost1372** [comment]
I agree

**Comment by ghost1372** [comment]
@GF-Huang can you upload a sample project with your converters?

**Comment by GF-Huang** [comment]
[ConverterDemo.zip](https://github.com/ghost1372/HandyControls/files/6177276/ConverterDemo.zip)

**Comment by ghost1372** [comment]
@GF-Huang I did not use the converter but used a dictionary instead
Please take a look to see if it meets your needs?

Create a array (description) first
```
<Window.Resources>
        <x:Array Type="sys:String" x:Key="desc">
            <sys:String>Left To Right Description</sys:String>
            <sys:String>Right To Left Description</sys:String>
        </x:Array>
    </Window.Resources>
```
and finally
        `<ComboBox ItemsSource="{Binding Source={local:DicBindingSource {x:Type FlowDirection}, {StaticResource desc}}}" DisplayMemberPath="Value"/>
`

DisplayMemberPath="Key" = this shows enum itself
DisplayMemberPath="Value" = this shows enum description

[WpfApp1.zip](https://github.com/ghost1372/HandyControls/files/6181164/WpfApp1.zip)


![Untitled](https://user-images.githubusercontent.com/9213496/111973065-bd39ed00-8b1b-11eb-8707-36dadde4bada.png)
