### ISSUE TITLE
Context menu is not in english

### ISSUE THREAD

**Issue by deviloper** [ghost1372/HandyControls#52]
**Describe the bug**
TabControl has a default context menu which is not in English as declared default.

**To Reproduce**
- Add HandyControls as NuGet package without specifying a language pack
- Instantiate a TabControl with a TabItem
- Richt-click on the tab header
- Here you can see a menu which is not in the default language

**Expected behavior**
I expected to see a context menu with commmands in english

**Screenshots**
![immagine](https://user-images.githubusercontent.com/5602328/111915547-303d5800-8a77-11eb-989a-95f3a22ef32b.png)

**Environment (please complete the following information):**
 - .net 5
 - Visual Studio 2019
 - HandyControls 3.2.0

**Comment by deviloper** [comment]
Sorry, moving to official repository.

**Comment by ghost1372** [comment]
Thank you, i will check it tomorrow

**Comment by ghost1372** [comment]
@deviloper 
i tested it and Everything works fine
It is better to attach a sample project so that I can better identify your problem
![Untitled](https://user-images.githubusercontent.com/9213496/111945190-d7150900-8af6-11eb-925e-bbf63ef58e16.png)

**Comment by deviloper** [comment]
Ok, that was my mistake, i wasn't using the language pack.

Now I initialized with `ConfigHelper.Instance.SetLang("en");` in App.xaml.cs and now it works fine!

Thank you, this is a very useful package!

**Comment by ghost1372** [comment]
you're welcome
Good luck
