### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ghost1372** [ghost1372/HandyControls#60]
@GF-Huang 
Unfortunately, the alternative I found was also limited, so I decided to Improve the previous localization which I had removed.
Finally, after a few hours, I succeeded, activating the design mode.😁
If you agree, I will return this version again
![11](https://user-images.githubusercontent.com/9213496/112713569-69504f00-8ef3-11eb-8d19-db77e0a227fa.gif)

[WpfApp12.zip](https://github.com/ghost1372/HandyControls/files/6215322/WpfApp12.zip)

**Comment by ghost1372** [comment]
Update:
Now we can use multiple resources 😄
But there is a problem

```
 <TextBlock Text="{hc:Localization data}"/>
 <TextBlock hc:LocalizationManager.TranslationProvider="WpfApp12;Assets.Resource" Text="{hc:Localization tom}"/>
 <TextBlock Text="{hc:Localization data}"/>
```
The last TextBlock is not translated and uses the wrong provider
![Untitled](https://user-images.githubusercontent.com/9213496/112718345-0a4d0300-8f10-11eb-97f9-189b719c4fe0.png)

[WpfApp12.zip](https://github.com/ghost1372/HandyControls/files/6215511/WpfApp12.zip)

**Comment by GF-Huang** [comment]
Seems it override the provider?

**Comment by ghost1372** [comment]
yes it get the Provider from another TextBlock which is not registered for itselft, it must take Provider from its parent
