### ISSUE TITLE
Is it required to reference HandyControl and HandyControls nuget packages both ?

### ISSUE THREAD

**Issue by YBAZAN** [ghost1372/HandyControls#61]
In the quick start, it is not clear if we have to reference HandyControl and HandyControls nuget packages both or if HandyControls is enough because it contains the other one ?

Thank for your help

**Comment by ghost1372** [comment]
@YBAZAN  You have to choose one of these, HandyControl is the official version, and HandyControls is the unofficial version (Which has all the features of the official version + more features) So you do not need to refer to both, you just have to choose one of them

**Comment by YBAZAN** [comment]
Thank you for your quick reply

**Comment by ghost1372** [comment]
your welcome And thanks for your suggestion, I updated the documentation It has become clearer now

**Comment by SwaroopSomanna** [comment]
I had previously installed both HandyControl and HandyControls. Now I've uninstalled HandyControl and kept HandyControls and getting reference error- "HandyControl could not be found" I tried replacing the word "HandyControl" with "HandyControls" in the codes but its not working. Also I tried to clean(successful) and rebuild (unsuccessful) the project and still doesn't work.

**Comment by ghost1372** [comment]
@SwaroopSomanna  check your csproj and app.xaml file
