### ISSUE TITLE
Difference between Loading and LoadingIndicator controls?

### ISSUE THREAD

**Issue by YBAZAN** [ghost1372/HandyControls#64]
As I looking deeper in this amazing WPF toolkit, I don't understand why there is Loading and LoadingIndicator controls ? They seem to be overlapping a little bit each other. 

I would say that Loading is the recommanded control as we find it in the Extended Controls page in the documentation site whereas LoadingIndicator documentation page is inside PersianToolkit area.

Would you give me some light on it?

**Comment by ghost1372** [comment]
They are not much different except that `Loading` Control has a base class (`LoadingBase`) and other loading effect have inherited from it (LoadingLine and LoadingCircle) but `LoadingIndicator` effects are defined in xaml style. On the other hand, LoadingIndicator is not available in the official version That is why it is located in the PersianToolkit area

**Comment by YBAZAN** [comment]
Thanks for your feedback. You would say that LoadingIndicator control offers more features and flexibility than Loading control ?

**Comment by ghost1372** [comment]
@YBAZAN  yes Loading has only 2 effects, but loadingIndicator has more effects
