### ISSUE TITLE
Does EnumDescriptionTypeConverter and LocalizedDescription works well for dynamic language change?

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#65]

**Comment by ghost1372** [comment]
It works well, But there is a small issue
You can see that the selected item changes according to the language but combobox not updated
I hope I can work on this at the right time
![3](https://user-images.githubusercontent.com/9213496/116463481-f898ab80-a87f-11eb-9183-a0ff03fb1be4.gif)

**Comment by GF-Huang** [comment]
> You can see that the selected item changes according to the language but combobox not updated

That's what I actually want to ask. 😄

**Comment by DineshSolanki** [comment]
I was going to ask the same thing, any update ?

**Comment by ghost1372** [comment]
not yet, I am still looking for a solution

**Comment by DineshSolanki** [comment]
Don't know if this is relevant or not, but I used to have a static field that I thought would obtain new value based on the switch case I written it, but it changed only once in the app life cycle,
So I used a method with the same switch case, and that static method worked perfectly

**Comment by DineshSolanki** [comment]
is it done?

**Comment by ghost1372** [comment]
> is it done?

No, I did not find a solution
