### ISSUE TITLE
hc:Localization design time error

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#67]
Run time no error, just design time. Refresh and rebuild not fix.

![image](https://user-images.githubusercontent.com/4510984/119201943-6a9c9300-bac2-11eb-9203-4e28fa90a849.png)

**Comment by ghost1372** [comment]
I do not know the exact source of the problem. But if you use the following solution, the problem will be solved
Choose **Only Display Platform Control**
![image](https://user-images.githubusercontent.com/9213496/119269460-105c1900-bc0d-11eb-8a4a-807c11b36cb7.png)

**Comment by ghost1372** [comment]
@GF-Huang Please test beta 11 to see if the issue is fixed or not

**Comment by GF-Huang** [comment]
Where's the beta 11?

**Comment by ghost1372** [comment]
you should use nightly build
https://hosseini.ninja/handycontrol/quick_start/#Nuget-Nightly-Builds

**Comment by GF-Huang** [comment]
BTW, why not push nightly or preview version to nuget?

**Comment by GF-Huang** [comment]
> @GF-Huang Please test beta 11 to see if the issue is fixed or not

Beta 11 works well.

**Comment by ghost1372** [comment]
> BTW, why not push nightly or preview version to nuget?

https://stackoverflow.com/a/23754621/3690982

**Comment by GF-Huang** [comment]
And what these mean? Could you give some examples/usage?

![image](https://user-images.githubusercontent.com/4510984/119317934-48199e00-bcab-11eb-9559-b1e7c162c688.png)

**Comment by ghost1372** [comment]
In fact, if you want to add a key along with other values you can use argument localization. but I tested it now and it seems to not work properly. I think I broke it when I added Multi Resources feature😭

![Untitled](https://user-images.githubusercontent.com/9213496/119322055-835ba300-bc92-11eb-8533-21d927ec753b.png)

To see its function, you can see this project
https://github.com/itabaev/wpflocalization

**Comment by ghost1372** [comment]
use this type of localization if you want to use key with arguments

create an array
```
 <Window.Resources>
        <x:Array x:Key="AbcStrings" Type="system:String">
            <system:String>A</system:String>
            <system:String>B</system:String>
            <system:String>C</system:String>
        </x:Array>
    </Window.Resources>
```
then
```
<TextBlock Grid.Row="0" Margin="5">
            <TextBlock.Text>
                <hc:Localization Key="ABC" Arguments="{StaticResource AbcStrings}" />
            </TextBlock.Text>
        </TextBlock>
```
also create a language key like this:
Name:ABC
Value: Alphabet {0}, {1}, {2}

result
![image](https://user-images.githubusercontent.com/9213496/119322863-552a9300-bc93-11eb-857c-bf65d0cbdf71.png)
