### ISSUE TITLE
Page XAML Designer doesn't load

### ISSUE THREAD

**Issue by davidepavani** [ghost1372/HandyControls#68]
**Describe the bug**

I'm trying to edit a xaml Page but the designer doesn't load the view.
all i can see is a (Very small) dot at the middle of the screen.

I added the DesignTimeResources.xaml for the itellisense as mentioned in the documentation. (also edited the .csproj and reloaded it)

i dont know if i'm doing something wrong but this issue slows down a bit my development.
What i'm doing right know is: creating a temporary user control and copy and paste the xml..

**To Reproduce**
Simply add to a wpf project (with HandyControls, obv) a Page (for a NavigationWindow)

**Screenshots**
![image](https://user-images.githubusercontent.com/80032950/119872449-c6807500-bf23-11eb-8433-530dcb78193f.png)

This is my XAML Designer

and my code is 

`<Page x:Class="Tengu.Classes.View.HomePage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:local="clr-namespace:Tengu.Classes.View"
      mc:Ignorable="d" 
      d:DesignHeight="500" d:DesignWidth="800"
      Title="HomePage">

    <Grid>
        <TextBlock Text="Test" 
                   VerticalAlignment="Center"
                   HorizontalAlignment="Center"
                   FontSize="30"
                   Foreground="White"/>
    </Grid>
</Page>`

Class:

`namespace Tengu.Classes.View
{
    /// <summary>
    /// Logica di interazione per HomePage.xaml
    /// </summary>
    public partial class HomePage : Page
    {
        public HomePage()
        {
            InitializeComponent();
        }
    }
}`

**Environment (please complete the following information):**
 - .Net core 5.0
 - IDE Visual Studio 2k19
 - HandyControls Version 3.3.5

I apologize in case i made a mistake in creating the report.
i love this library a lot!!

**Comment by Dugongoo** [comment]
thank you very much for the quick reply.
I will wait for any updates!
