### ISSUE TITLE
Added French translation

### ISSUE THREAD

**Issue by BadNiiw** [ghost1372/HandyControls#7]
Hi @ghost1372 , I'm sorry to open an issue even if it isn't one but I added French translation and full french support for the HandyControlDemo.

Here are the files : 
[HandyControlDemo_Shared.Langs.fr.resx.zip](https://github.com/ghost1372/HandyControls/files/3509198/HandyControlDemo_Shared.Langs.fr.resx.zip)
[HandyControl_Shared.Lang.fr.resx.zip](https://github.com/ghost1372/HandyControls/files/3509200/HandyControl_Shared.Lang.fr.resx.zip)

**Comment by BadNiiw** [comment]
French flag icon 
![fr](https://user-images.githubusercontent.com/17864005/63163727-8ee25a80-c026-11e9-8c2c-d470321a9588.png)

**NoUserContent.xaml** : added french translation button

`<Button Tag="fr" Style="{StaticResource ButtonCustom}" Margin="0,10,0,0">
                        <Image Width="32" Source="/HandyControlDemo;component/Resources/Img/Flag/fr.png"/>
                    </Button>`

**HandyControlDemo_Net_GE45.csproj** : added french flag as resource 

`<Resource Include="..\..\Shared\HandyControlDemo_Shared\Resources\Img\Flag\fr.png">
      <Link>Resources\Img\Flag\fr.png</Link>
    </Resource>`

**HandyControl_Net_GE45.csproj** : added french french resource file 

` <EmbeddedResource Include="..\..\Shared\HandyControl_Shared\Properties\Langs\Lang.fr.resx">
      <Link>Properties\Langs\Lang.fr.resx</Link>
    </EmbeddedResource>`

**Comment by ghost1372** [comment]
hi @BadNiiw  Thank you for your participation. I'll add French in a few moments
I'm glad to hear that You can fork and translate an existing wiki and finally publish it on your repository. I will add the link to the wiki page.

**Comment by BadNiiw** [comment]
@ghost1372 Started the french Wiki : https://github.com/BadNiiw/HandyControl/wiki/

**Comment by ghost1372** [comment]
@BadNiiw  i added a link to first page thank you👍
https://github.com/ghost1372/HandyControl/wiki

**Comment by BadNiiw** [comment]
@ghost1372 Ugh, seems I cannot go into edit mode of your Wiki anymore. I used to copy the markdown code into mine and then edit it. Now it's a bit more difficult and time consuming.
Would you minde giving me edit access for the Wiki until I finish ?
Btw, do you have something like Skype or whatever so we could talk ? :)

**Comment by ghost1372** [comment]
@BadNiiw Yes I disabled editing but you can clone it and push to your wiki
```
https://github.com/ghost1372/HandyControl.wiki.git
```
If this does not satisfy you
  Notify me to re-enable editing

Unfortunately no 😅

**Comment by BadNiiw** [comment]
@ghost1372 Oh perfect, just cloned the Wiki
Okay no problem. At least you seem to be quite active on Github so it's fine  👍

**Comment by ghost1372** [comment]
@BadNiiw  i added gitter chat 
https://gitter.im/HandyControls/community
