### ISSUE TITLE
Using both (Persian and Gregorian) calendars in single control and custom month names for PersianCalendar

### ISSUE THREAD

**Issue by hussain1368** [ghost1372/HandyControls#70]
1. Would be very nice if the PersianCalendar control would be able to render both Gregorian and Persian calendars based on may be a **DependencyProperty** like **IsGregorian**? That would be great for multi-culture applications.
2. Custom month names for Persian calendar would be very useful. for example if I need to use **"Dari"** month names like **(حمل)** instead of **(فروردین)** and **(ثور)** instead of **(اردیبهشت)**.
Thanks

**Comment by ghost1372** [comment]
در خصوص قسمت دوم، امکان اینکه بصورت پراپرتی ازش استفاده بشه نیست، حداقل فعلا نتونستم ازش نتیجه بگیرم
راه حلی که وجود داره اینه که بصورت توکار از اسامی افغانستان پشتیبانی بشه و با تغییر کالچر برنامه اسامی تغییر کنه که این براحتی شدنی هست
نظری در این خصوص دارید؟

**Comment by hussain1368** [comment]
تاریخ ایران و افغانستان دقیقا یکسان هست. بله امروز در افغانستان هم 10 خرداد هست. تنها چیزی که فرق میکنه نام ماه ها هست که بجای نامهای پهلوی از نامهای صور فلکی استفاده میشود ، یعنی حمل، ثور، جوزا و ...
در مورد اینکه گفتید "توکار" استفاده بشه، منظورتان اینه که باید در سورس کود تغییر بیارم و اون رو خودم کومپیال کنم؟ یعنی دیگه از پیکیج nuget نمیتوانم استفاده کنم؟

**Comment by ghost1372** [comment]
نه منظورم از توکار به این صورت هست که اسامی داخل سورس کد نوشته میشه و با تغییر کالچر بصورت خودکار اسامی متناسب با کالچر نمایش داده میشه شما از همون بسته ناگت استفاده میکنید فقط قبل از اینکه برنامه اجرا بشه کد زیر رو بنویسید 

`System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("fa-AF");`

در خصوص کدهای زبان که نوشتم اطلاعی ندارید؟
ایا دری و پشتو هم مثل هم هستن؟

**Comment by hussain1368** [comment]
دری و پشتو دو تا زبان رسمی در افغانستان هستند. اما نام ماه ها در بین دو زبان مشترک هستند

**Comment by hussain1368** [comment]
دری و پشتو دو تا زبان رسمی در افغانستان هستند. اما نام ماه ها در بین دو زبان مشترک هستند

**Comment by ghost1372** [comment]
لطفا اسامی ماه هارو به ترتیب (فروردین، اردیبهشت ...) برام بنویسید چون من اطلاعی از اسامی دقیق ندارم
همچنین ایا اسامی روزهای هفته مثل ایران (شنبه، یکشنبه ...) هست؟
بین صبح و عصر که تو افغانستان تفاوتی نیست؟
منظور کلمه صبح و عصر هست

**Comment by ghost1372** [comment]
پشتیبانی از اسامی رو اضافه کردم
توسط هرکدوم از کدهای زیر میتونید از تقویم فارسی با نام های افغانستان استفاده کنید
`System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("fa-AF");
`
یا

`System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("ps-AF");
`
یا

`System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("prs-AF");
`

البته اگر بتونم راه حل ساده تر و بهتری پیدا بکنم قطعا جایگزین میشه، نحوه استفاده هم بزودی در مستندات نوشته میشه
از اینجا میتونید پیگیری کنید

https://hosseini.ninja/handycontrol/persianToolkit/persianCalendar/

بسته ناگت هم انشالله یکی دو هفته ای اپلود میکنم
![image](https://user-images.githubusercontent.com/9213496/120191993-e075cc80-c22f-11eb-85bf-f3c9543a27bb.png)

**Comment by hussain1368** [comment]
ممنون از زحمات شما.
منتظر بروزرسانی ناگت هستم

**Comment by hussain1368** [comment]
سلام و صبح بخیر
هنوز از بروزرسانی بسته ناگت خبری نیست؟
تشکر

**Comment by ghost1372** [comment]
سلام روز بخیر
چند روزی هست کمی سرم شلوغ هست انشالله تا چند روز اینده بسته ناگت رو اپلود میکنم
اگر خیلی عجله دارید میتونید از بسته ناگت شبانه استفاده کنید تا کارتون راه بیوفته
دستورالعمل استفاده رو اینجا توضیح دادم
https://hosseini.ninja/handycontrol/quick_start/#Nuget-Nightly-Builds

**Comment by ghost1372** [comment]
> سلام و صبح بخیر
> هنوز از بروزرسانی بسته ناگت خبری نیست؟
> تشکر

بسته ناگت نسخه 3.3.6 منتشر شد

**Comment by hussain1368** [comment]
تشکر از اینکه اطلاع دادید

**Comment by hussain1368** [comment]
یک اتفاق عجیب افتاده. وقتی از استایل متریال استفاده میشه ماه های افغانستان نشان داده نمیشه اما با استایل دیفالت درسته
```
public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            var culture = new CultureInfo("prs-AF");
            //culture.NumberFormat = new CultureInfo("en-US").NumberFormat;
            //culture.DateTimeFormat = new CultureInfo("en-US").DateTimeFormat;

            System.Threading.Thread.CurrentThread.CurrentCulture = culture;

            base.OnStartup(e);
        }
    }
```
![Screenshot 2021-06-17 144606](https://user-images.githubusercontent.com/36886947/122379049-bf291600-cf7b-11eb-8150-ed64495b7eb8.png)

**Comment by ghost1372** [comment]
در حالت ماه، همه چیز درسته، باز بررسی میکنم
![image](https://user-images.githubusercontent.com/9213496/122390129-e46f5180-cf86-11eb-8a14-317ed68b8d3a.png)

**Comment by hussain1368** [comment]
من یک نگاهی انداختم. ماه های ایرانی دو جا تعریف شدن:
`PersianCalendarHelper and PersianDateTime`
فکر کنم این یکی از قلم افتاده:
```
        private static readonly string[] months =
            {"", "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"};
```

**Comment by ghost1372** [comment]
PersianDateTime
مربوط به تقویم نیست و خودش شامل یه کلاس هلپر برای کار با تاریخ هست کلا ارتباطی با تقویم نداره
مشکل جای دیگه هست سعی میکنم رفعش کنم

**Comment by ghost1372** [comment]
مشکل مربوط به متریال دیزاین هستش قسمت
PART_HeaderButton و CurrentDateTextBlock و CalendarYearMonthConverter
سه قسمت اضافی هستن که داخل قالب پیشفرض تقویم وجود ندارن و متریال دیزاین خودش این قسمت هارو اضافه کرده و با روش خودشون اون رو پر میکنن
در نتیجه شما باید از تیم متریال دیزاین بخواین که اسامی نام های افغان رو چک کنن و راه تغییر زبان تقویم رو ازشون بپرسید چون مثل اینکه
Language="fa-AF"
جواب نمیده

**Comment by hussain1368** [comment]
ممنون. حتما همین کارو میکنم

**Comment by hussain1368** [comment]
سلام مجدد
سورس متریال کیت رو دیدم. کالچر خودش رو از این میگیره
 `XmlLanguage.GetSpecificCulture` 
 بالاخره مجبور شدم تمام فایلهای زیر رو کپی کنم و داخل پروژه خودم تغییرشان بدم
```
CalendarYearMonthConverter.cs
MaterialDateDisplay.cs
MaterialDateDisplay.xaml
```
همچنین چون 
`PersianCalendarHelper` 
شما هم از نوع
 `internal` 
بود مجبور شدم اونم کپی کنم.
شما راهی بلد نیستین که بتونیم کالچر 
`XmlLanguage`
 رو سفارشی کنیم؟ من خیلی سیرچ کردم و به نتیجه نرسیدم. گرچند فعلا کارم پیش میره اما خیلی کود از داخل هر دو پکیج زیاد بیرون آوردم. نمیدونم روش خوبی هست یا نه

![Screenshot 2021-06-28 171055](https://user-images.githubusercontent.com/36886947/123640584-8ff58d00-d836-11eb-847f-ed465a6ca53d.png)

**Comment by ghost1372** [comment]
ن والا راهی به ذهنم نمیرسه البته فکر نکنم نیاز باشه همه چیو کپی کنید شاید بتونید اون متدهای اصلی که دخیل هستند رو یجوری 
override 
کنید تا مشکل حل بشه

**Comment by hussain1368** [comment]
من هم تلاش کردم همون کار کنم. اما مشکل اینجاست که همه کلاسایی و متودایی که کپی کردم یکی از این سه حالت داشتن
private, internal, sealed

**Comment by mahdiataey** [comment]
سلام ممنونم از زحمات شما بابت این پکیج
میشه لطف کنین بگین چجوری میشه فرمت تاریخ را از شورت به لانگ تغییر داد ممنون؟
