### ISSUE TITLE
hc:MenuAttach.IsEnabledAnimation="False" not works

### ISSUE THREAD

**Issue by GF-Huang** [ghost1372/HandyControls#73]
`hc:MenuAttach.IsEnabledAnimation="False"` not works in 3.3.6-beta.19, same code in 3.3.5 works well.

**Comment by ghost1372** [comment]
I will check soon

**Comment by ghost1372** [comment]
fixed in https://github.com/ghost1372/HandyControls/commit/0c5a0548451fb32cbaa716b52ed819f7ba66181f
