### ISSUE TITLE
How Can i apply custom styles in HandyControls

### ISSUE THREAD

**Issue by GaneshSingaravelu** [ghost1372/HandyControls#79]
Hi,

I am using HandyControls in my WPF application. Since I need to add my custom style in the textbox. However, if I add my style in the textbox it overrides the HandyControls styles and it won't work as expected. Please let me know how to derive (BasedOn) HandyControl styles in my custom styles

Issue:
     "Infoelement placeholder" didn't work If I add my custom style in the textbox.

Style
 ```
<Window.Resources>        
       <Style x:Key="NormalTextBoxStyle" TargetType="{x:Type TextBox}">
        <Style.Resources>
            <Style TargetType="{x:Type Border}">
                <Setter Property="Height" Value="30" />
                <Setter Property="Width" Value="300" />
                <Setter Property="Padding" Value="5 4 0 0" />
                <Setter Property="HorizontalAlignment" Value="Left" />
            </Style>
        </Style.Resources>
    </Style>
   </Window.Resources>
```
XAML

```
 <hc:TextBox Name="Name"
                 Grid.Row="5"
                 Grid.Column="1"
                 Margin="5 0 0 0"
                 Style="{StaticResource NormalTextBoxStyle}"
                hc:InfoElement.Placeholder="Please enter the name"
                 HorizontalAlignment="Left" 
                 Focusable="True"></hc:TextBox>
```
**Environment (please complete the following information):**
 - .net: [4.5.2]
 - IDE [e.g. vs2019]
 - Version [e.g. 16.7.7]

Thanks

**Comment by ghost1372** [comment]
I can see that you wrote the style for the **Textbox** but you are using the **hc:Textbox** The two are different.
I do not know what you are going to do but if you want to expand the existing styles you have to create the following styles

fot **TextBox**
```
<Style TargetType="TextBox" BasedOn="{StaticResource TextBoxBaseStyle}">
    
</Style>
```

for **hc:TextBox**

```
<Style TargetType="hc:TextBox" BasedOn="{StaticResource TextBoxPlusBaseStyle}">

</Style>
```

in this way you do not lose InfoElement.Placeholder
But if you want to do not use HandyControl styles You need to create the following style

```
<Style TargetType="TextBox" BasedOn="{StaticResource {x:Type TextBox}}">

</Style>
```
and in this way you will lose InfoElement.Placeholder

**Comment by ghost1372** [comment]
> Thanks, @ghost1372, It is working now. Can u give me the style name ('Basedon') for ComboBox?

see [here](https://github.com/ghost1372/HandyControls/blob/develop/src/Shared/HandyControl_Shared/Themes/Styles/ComboBox.xaml)
 and [here](https://hosseini.ninja/handycontrol/native_controls/comboBox/)
you can find styles name from docs and source code

anyway, for Combobox => **ComboBoxBaseStyle**
for hc:ComboBox => **ComboBoxPlusBaseStyle**
