### ISSUE TITLE
[Feature request] Global Data helper, if the path doesn't exist, create it.

### ISSUE THREAD

**Issue by DineshSolanki** [ghost1372/HandyControls#83]
**Is your feature request related to a problem? Please describe.**
currently, I have to manually create the path first before using a custom name with the path that might not exist already.

**Describe the solution you'd like**
```csharp
public override string FileName { get; set; } =
         Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"foo","bar","AppConfig.json");
```
if the above folders. foo & bar does not exist, Data helper should create them, before creating AppConfig.json.

**Additional context**
This method might come in handy
```csharp
public static void CreateFile(string fullFilePath)
        {
            var fileName = Path.GetFileName(fullFilePath);
            var pathWithoutFileName = fullFilePath.Replace(fileName, "");
            Directory.CreateDirectory(pathWithoutFileName);
            if (string.IsNullOrEmpty(fileName))
				fileName = "AppConfig.json";
            File.Create(Path.Combine(pathWithoutFileName, fileName));
        }
```

**Comment by ghost1372** [comment]
If filename is empty or null, AppConfig.json file will be created next to the executable file. As far as I know there is no need to create a folder and it is created automatically

**Comment by DineshSolanki** [comment]
> 
> 
> If filename is empty or null, AppConfig.json file will be created next to the executable file. As far as I know there is no need to create a folder and it is created automatically

consider a situation where I give a fileName with full path, because I also want to change the path, and not want to place it next to executable,
then if the path does not exist, it will throw an exception.
```csharp
if (string.IsNullOrEmpty(fileName))
	fileName = "AppConfig.json";
```
and the above check is for situations, where we want to only give the path.

**Comment by ghost1372** [comment]
Done
