### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jhm-ciberman** [ghost1372/HandyControls#88]
We are in the final stage of developing our new software using HandyControls. Currently we are using HandyControls v3.3.7 but we would benefit a lot of the new features (Mainly the Spanish translations but also the new "DataGrid.Small" and some bugfixes with the TextBox component error validation.)

Any possibility in having a new release? 
I've tried using the MyGet builds but they seem a little unstable and crash or fail. 

btw: thanks for contributing to such amazing library <3 Love it

**Comment by ghost1372** [comment]
Hi I apologize for the delay
It's been a week since my laptop has been down (Accidentally spilled liquid on the keyboard😁)
The laptop will come back from warranty Tomorrow or the day after tomorrow
I will release a new nuget version this weekend

**Comment by jhm-ciberman** [comment]
Oh, no hurries! Probably there is at least one month more until we prepare for release. 
Hope your laptop works fine after the service. 
And thanks again for being so helpful

**Comment by ghost1372** [comment]
v3.3.8 released
https://www.nuget.org/packages/HandyControls/3.3.8

**Comment by jhm-ciberman** [comment]
Thank you @ghost1372 for this release. It works amazing! 

One little thing, all the combo box drop down menus now look shifted to the right:

![image](https://user-images.githubusercontent.com/7988351/135863399-3691213f-b7d0-49c7-8f69-9987c3ab5d8c.png)

![image](https://user-images.githubusercontent.com/7988351/135863597-35a20667-b546-41c2-9bd9-f70383fb1139.png)

![image](https://user-images.githubusercontent.com/7988351/135863766-746bb3e3-eed4-4e91-b3c9-cdbf50b72f23.png)

Do you recommend me to apply some global style to fix everything? Or should I wait for a next release?

**Comment by ghost1372** [comment]
Hi @jhm-ciberman this is new style for combobox (introduced in last [commit](https://github.com/HandyOrg/HandyControl/commit/5dcb6dc64915d66a8bb2f16ba68373587a1fa7ff))
If you do not like it, you have to modify the combobox style yourself

**Comment by jhm-ciberman** [comment]
Oh, thank you. Honestly, it looks terrible. I thought it was a bug. I wonder why did they changed it. I will try to create my own style then. Hope they revert it in the next version. I will open an issue in the original repo to ask. 

Thank you!

**Comment by ghost1372** [comment]
Yes, I think the decision was a bit hasty

**Comment by ghost1372** [comment]
@jhm-ciberman FYI
new version 3.3.8.1 released in nuget with combobox design fix

**Comment by ghost1372** [comment]
Unfortunately, nabian is very busy this days and Many requests have not been processed. But these problems will definitely be solved soon.
