### ISSUE TITLE
[Feature request] windows 11 context menu entries support

### ISSUE THREAD

**Issue by DineshSolanki** [ghost1372/HandyControls#90]
**windows 11 context menu integration methods**
Right now, the shell!/context menu command that we add by handycontrols, are shown in a new "show more options" menu of windows 11 context menu. 
It would be great to have an option to avoid that. 

**we can check if windows os is 11, and then add entries in windows 11 fashion else same as before**

**Comment by ghost1372** [comment]
> surprisingly this shows up in the windows 11 context menu https://www.howtogeek.com/howto/windows-vista/add-take-ownership-to-explorer-right-click-menu-in-vista/ ![image](https://user-images.githubusercontent.com/15937452/137631884-29f2d2cb-6449-4f9e-87b8-13e1a481681f.png)
> 
> TL:DR:
> 
> ```shell
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\*\shell\runas]
> @="Take Ownership"
> "NoWorkingDirectory"=""
> 
> [HKEY_CLASSES_ROOT\*\shell\runas\command]
> @="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> 
> [HKEY_CLASSES_ROOT\Directory\shell\runas]
> @="Take Ownership"
> "NoWorkingDirectory"=""
> 
> [HKEY_CLASSES_ROOT\Directory\shell\runas\command]
> @="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
> "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
> ```

Did you test? Does it only work for this option or can any other item be added?

**Comment by DineshSolanki** [comment]
> 
> 
> > surprisingly this shows up in the windows 11 context menu [howtogeek.com/howto/windows-vista/add-take-ownership-to-explorer-right-click-menu-in-vista](https://www.howtogeek.com/howto/windows-vista/add-take-ownership-to-explorer-right-click-menu-in-vista/) ![image](https://user-images.githubusercontent.com/15937452/137631884-29f2d2cb-6449-4f9e-87b8-13e1a481681f.png)
> > TL:DR:
> > ```shell
> > Windows Registry Editor Version 5.00
> > 
> > [HKEY_CLASSES_ROOT\*\shell\runas]
> > @="Take Ownership"
> > "NoWorkingDirectory"=""
> > 
> > [HKEY_CLASSES_ROOT\*\shell\runas\command]
> > @="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> > "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
> > 
> > [HKEY_CLASSES_ROOT\Directory\shell\runas]
> > @="Take Ownership"
> > "NoWorkingDirectory"=""
> > 
> > [HKEY_CLASSES_ROOT\Directory\shell\runas\command]
> > @="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
> > "IsolatedCommand"="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
> > ```
> 
> Did you test? Does it only work for this option or can any other item be added?
> 
> UPDATE: I tested and I was able to successfully create another key, but the problem is that it runs as an admin

Yes, I tested and apart from running as admin(which is because it is in 'runas') it seems to only work for folder context and not directory background context.
I tried to port one of my old context entries- 
```bash
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\runas]
@="Merge Subtitles"
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\shell\runas\command]
@="\"C:\\Users\\solan\\Downloads\\Compressed\\BatchMuxer.Subtitle-Console.v1.0_Win_x64\\BatchMuxer_Subtitle_Console.exe\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\Background\shell\runas]
@="Merge Subtitles"
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\Background\shell\runas\command]
@="\"C:\\Users\\solan\\Downloads\\Compressed\\BatchMuxer.Subtitle-Console.v1.0_Win_x64\\BatchMuxer_Subtitle_Console.exe\" \"%V\""
```

Background\shell only shows in 'Show more options'

**Comment by DineshSolanki** [comment]
comment from WinRAR dev - https://github.com/SamuelTulach/VirusTotalUploader/issues/95#issuecomment-970564843

**Comment by ghost1372** [comment]
> comment from WinRAR dev - [SamuelTulach/VirusTotalUploader#95 (comment)](https://github.com/SamuelTulach/VirusTotalUploader/issues/95#issuecomment-970564843)

As far as I know,currently the only way is to use C++
