### ISSUE TITLE
Fix "NotifyIcon" control disappear of taskbar restart

### ISSUE THREAD

**Issue by Jie2GG** [ghost1372/HandyControls#91]
**Describe the bug**
The notify icon disappear of taskbar restart

**To Reproduce**
1. The open notify icon with application
2. restart explorer.exe

**Expected behavior**
notify icon disappear

**Screenshots**
None

**Environment (please complete the following information):**
 - .NET 5.0
 - Visual Studio 2019
 - Version 3.3.8.1

**Additional context**
I tried to use "WM_TASKBARCREATED" message the solve issues
```cs
public sealed class TaskbarRebuildBehavior : Behavior<System.Windows.Window>
{
	#region --字段--
	public static readonly DependencyProperty ElementProperty = DependencyProperty.Register ("Element", typeof (UIElement), typeof (TaskbarRebuildBehavior));
	private int taskbarCreated;
	#endregion

	#region --属性--
	/// <summary>
	/// 获取或设置重建的元素
	/// </summary>
	public UIElement Element
	{
		get => (UIElement)this.GetValue (ElementProperty);
		set => this.SetValue (ElementProperty, value);
	}
	#endregion

	#region --公开方法--
	protected override void OnAttached ()
	{
		this.AssociatedObject.Loaded += (sender, e) =>
		{
			this.taskbarCreated = Win32_RegisterWindowMessage ("TaskbarCreated");
			if (PresentationSource.FromVisual (this.AssociatedObject) is HwndSource hwndSource)
			{
				hwndSource.AddHook (this.WndProc);
			}
		};
	}
	#endregion

	#region --私有方法--
	private IntPtr WndProc (IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
	{
		if (msg == this.taskbarCreated)
		{
			this.Element.Visibility = Visibility.Collapsed;
			this.Element.Visibility = Visibility.Visible;
		}
		return IntPtr.Zero;
	}
	#endregion

	#region --API--
	[DllImport ("user32.dll", EntryPoint = "RegisterWindowMessage", CharSet = CharSet.Unicode, SetLastError = true)]
	private static extern int Win32_RegisterWindowMessage (string lpString);
	#endregion
}
```

**Comment by ghost1372** [comment]
Hi, Thank you
Does this work on `hc:Window` as well?

**Comment by Jie2GG** [comment]
> Hi, Thank you Does this work on as well?`hc:Window`

Yes, be suitable **hc:window**

**Comment by ghost1372** [comment]
so this code
`TaskbarRebuildBehavior : Behavior<System.Windows.Window>`
will work with hc:Window? or we need to create another class for hc:Window?

**Comment by Jie2GG** [comment]
> so this code will work with hc:Window? or we need to create another class for hc:Window?`TaskbarRebuildBehavior : Behavior<System.Windows.Window>` `TaskbarRebuildBehavior : Behavior<HandyControl.Controls.Window>`

You can go directly to **hc:Window** used. 
```xml
<hc:Window>
	<hc:NotifyIcon x:Name="NotifyIcon"/>
	<behaviors:Interaction.Behaviors>
		<behavior:TaskbarRebuildBehavior Element="{Binding ElementName=NotifyIcon}" />
	</behaviors:Interaction.Behaviors>
</hc:Window>
```

**Comment by ghost1372** [comment]
Thank you, I tested and it works.
I'm looking for a way to use this class built-in in hc

**Comment by ghost1372** [comment]
I tried different ways but it did not work internally, so i added `TaskbarRebuildBehavior.cs` in hc but I refer to it in the documentation so that users can solve this problem themselves by adding behavior in xaml

**Comment by ghost1372** [comment]
Hi @Jie2GG 
It seems **TaskbarRebuildBehavior** not works if we define the NotifyIcon in App.xaml. 
https://github.com/HandyOrg/HandyControl/issues/830#issuecomment-1001065437

do you have any idea?

**Comment by Jie2GG** [comment]
@ghost1372 I am checking the this problem

**Comment by Jie2GG** [comment]
@ghost1372 
Hi, I feel add hook to **NotifyIcon** control beeter. 
Please note that my **TaskbarRebuildBehavior** code, **AddHook** and **RemoveHook** is load event and unload event.
if **NotifyIcon** can use load and unload event, can copy code to NotifyIcon.
1. register hook 'TaskbarCreated' in load event.
2. unregister hook 'TaskbarCreated' in unload event.
