### ISSUE TITLE
Set Language doesn't work on Persian Date Picker 

### ISSUE THREAD

**Issue by serajoddin-aliabadi** [ghost1372/HandyControls#92]
**Describe the bug**
ConfigHelper.Instance.SetLang("en");  doesn't work on Persian Date Picker 

**Expected behavior**
In official Date Picker SetLang method works and changes date picker language.

**Environment (please complete the following information):**
 - .net: 5
 - IDE: vs2022
 - Version 3.3.8

**Comment by ghost1372** [comment]
Yes Does not work because it is PersianDatePicker
you can use DatePicker

**Comment by serajoddin-aliabadi** [comment]
> Yes Does not work because it is PersianDatePicker you can use DatePicker

I Know it is Persian Date Picker! but if we need switch between PersianDatePicker (fa) and another culture like en-us, mentioned code doesn't work.

Thanks.

**Comment by ghost1372** [comment]
i removed gregorian support from PersianDatePicker because something is wrong and month name displayed inccorect.
anyway you can track this feature here
https://github.com/ghost1372/HandyControls/issues/70
