### ISSUE TITLE
lost resource when referrence wfp project in a console app

### ISSUE THREAD

**Issue by Blame4** [ghost1372/HandyControls#93]
**Describe the bug**
I referrenced a wfp project in a console app.  calling Window.ShowDialog(). I'ok with official version of handyControl. 
For example, add style ="{StaticResource ButtonPrimary}" to a button.
It's blue with handyControl, but white with handyControls.

**To Reproduce**
1. Create a handyControls Project
2. Add a button with style="{StaticResource ButtonPrimart}"
3. Create a Console App
4. Call MainWindow.ShowDialog() in Program.cs
5. Run the Console App
6. See.if the button is blue

**Expected behavior**
The button should be blue

**Screenshots**

**Environment (please complete the following information):**
 - .net: 4.8
 - IDE vs2019
 - Version 3.3.8.1

**Additional context**

**Comment by ghost1372** [comment]
please upload a demo project

**Comment by Blame4** [comment]
here is the demo
[https://github.com/Blame4/HandyControl-s-Project](url)

**Comment by ghost1372** [comment]
Thanks, but your example does not run 😕
![image](https://user-images.githubusercontent.com/9213496/140956788-ad3d1deb-2b24-43b3-90e4-42ec90ad792a.png)

**Comment by Blame4** [comment]
Yes, I got that too. You just need to rebuilt it.

**Comment by Blame4** [comment]
Yes, I got that too. You just need to rebuilt it.

**Comment by ghost1372** [comment]
@Blame4 Theme Manager is different in HandyControls and HandyControl
However you can use the following dictionaries and the problem will be solved

`<ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Basic/Colors/Light.xaml"/><ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>`

**Comment by Blame4** [comment]
Thanks, That solves my problem. It's good to have HandyControls in Plugin development. Nice and Quick.
