### ISSUE TITLE
[BUG] Mica effect bug

### ISSUE THREAD

**Issue by MichixYT** [ghost1372/HandyControls#99]
Mica effect does not work with `ResizeMode="NoResize"`

**Comment by ghost1372** [comment]
https://github.com/HandyOrg/HandyControl/pull/1037#issuecomment-981398624

**Comment by ghost1372** [comment]
Fixed in https://github.com/ghost1372/HandyControls/commit/37697c5544717c1a73ce380e4e2691dd66de71dd
